### ISSUE TITLE
sw-appcache-behavior network/fallback tests

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#11]
The current tests for `sw-appcache-behavior` cover cache population, but don't test the expected `NETWORK`/`FALLBACK` behavior. Those tests need to be written.

**Comment by gauntface** [comment]
@jeffposnick is this still something you wish to look at?

**Comment by jeffposnick** [comment]
Yup.

**Comment by jeffposnick** [comment]
Closing, as `sw-appcache-behavior` has been moved, and this would be on the radar if/when we re-implement.
