### ISSUE TITLE
README: Add note about npm install/yarn root

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#132]
Minor one. When you clone sw-helpers, it's not clear right now what the expectation would be when you `npm install` or `yarn` root. 

One might guess this will recursively try installing all the dependencies for the sub-packages in the mono-repo. Or just the deps needed to hack on sw-helpers, but since we don't appear to note this in the readme it's unclear.

**Comment by addyosmani** [comment]
Further feedback:
- We should tell folks that they'll need to run `gulp` in order to build the packages
- Might be useful to note whether you can individually build a subpackage and how (e.g do you need to build everything as they rely on each other as dependencies)

**Comment by gauntface** [comment]
@addyosmani I added this to the docs: https://googlechrome.github.io/sw-helpers/contributing.html#main

I think this addresses the above issues, let me know if not.
