### ISSUE TITLE
Add README (installation + usage instructions) for sw-cli

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#133]
**Library Affected**:
*sw-cli*

**Browser & Platform**:
*All browsers/platforms*

**Issue or Feature Request Description**:
I believe we have an issue tracking usage over in https://github.com/GoogleChrome/sw-helpers/issues/82. This is a quick reminder for us to also include installation instructions at the root of the sw-cli package along with how to use it. Feel free to close as a dupe of #82 if we're going to cover installation there too.

**Comment by addyosmani** [comment]
Note for anyone using the CLI: you'll want to `gulp build --project sw-cli` to get it working.

**Comment by gauntface** [comment]
We now an entry in the readme for the sw-cli, some details in the reference docs and we have it published on NPM, so I feel like this can be closed for now - please re-open if you disagree.
