### ISSUE TITLE
sw-precaching and Routing

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#136]
sw-precaching at the moment ONLY caches assets, it doesn't define any routes.

There are a few things to consider:

1. If it sets up the routes inside the module, that blocks off any possibility of external routes doing the caching.
1. If we want external routes to be defined to do this, there is no exposure of the cache name and be default I think caching strategies look in a custom cache name.

Solutions:
1. Add the routes in sw-precaching.
1. Add the routes in sw-precaching with opt out in options.
1. Add a way for routes to match against any cache (i.e. caches.matches() )
1. Add a way to get the cache name from sw-precaching and configure route for that.

**Comment by jeffposnick** [comment]
How about this? (I think it's pretty similar to what was in a design doc somewhere.)

```js
const precacheManager = new goog.precaching.PrecacheManager();
// Do stuff with precacheManager to set up the manifest, etc....

const router = new goog.routing.Router();

// This would create a Route that new exactly which URLs to match and would use a
// cache-first strategy as the handler.
const precacheRoute = precacheManager.createRoute();
router.registerRoute({route: precacheRoute});

// Register any additional runtime routes at this point.
```

That's the lower-level picture, of course. Maybe there's an opportunity to have `sw-lib` paper over some of the details?

**Comment by gauntface** [comment]
That sounds like a good mix of giving the developer choice when using the module directly and sw-lib can super easily make this so.

Will make a PR for this to see what you think of an approach.

**Comment by jeffposnick** [comment]
Here's another wrinkle: `sw-precache` currently supports fallback-to-App Shell-for-navigation-request style routing via a combination of the [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string) and [`navigateFallbackWhitelist`](https://github.com/GoogleChrome/sw-precache#navigatefallbackwhitelist-arrayregexp) options.

Routing navigation requests to the cached App Shell is an important use case, so we should address it somehow:

1. The proposed `precacheManager.createRoute()` method can take in additional parameters equivalent to `navigateFallback`/`navigateFallbackWhitelist` (but hopefully named something better). Then the `Route` it creates could handle navigation requests appropriately. This presupposes that everyone using the App Shell architecture will also be using `PrecacheManager`.

2. Create a new `AppShellRoute` subclass of `Route` that behaved much the same way, but wasn't as tied to `PrecacheManager`. This would be more flexible, but it means more things for a developer to configure and/or forget to include. Some of that additional developer pain might be smoothed over by a `sw-lib` abstraction, though.

3. Something else?

If we go with 1., it would probably fall to @gauntface as part of the related work tracked in this issue. If we go with 2., I'll file a separate issue and assign it to myself.

**Comment by gauntface** [comment]
Thinking on this a little more and struggling to picture the best way to do it with the current API.

The fact we are even discussing the navigateFallback in relation to precache management is a bit of a wake up call that this might not be the best approach.

An alternative approach to the above is to just not include routing with precaching and instead expose the required details so a Route could be constructed. Developers could use the cacheName to check the specific cache and return cacheFirst or cacheOnly for those values.

The question becomes, what is needed to construct the precache route?

The `match` callback on the `Route` class is the awkward piece. Because it doesn't allow async responses, we need to know up front what URL's can be handled. Precache could make an array of URLs available and the `match` callback can test against that and then use `CacheFirst` handler, making the  `cacheName` exposed on precacheManager.

Basically we'd up with something along these lines (Ignoring the URL parsing / dance to make them actually the same format):

    precacheManager.cacheRevisionedAssets([........]);
    const route = new Route({
        match: ({url, event} => {
          const cachedUrls = precacheManager.getCachedUrls();
          if (cachedUrls.indexOf(url) !== -1) {
            return true;
          }
          return false;
        }),
        handler: new CacheFirstHandler({
            cacheName: precacheManager.getCacheName()
        })
    });

This approach *could* be abstracted to a seperate Route that can wrap this up nicely. Either way, sw-lib can (and will) abstract this away from.

This approach would then also leave the navigateFallback to a seperate discussion as to how it's handled amongst other routes.

**Comment by jeffposnick** [comment]
Hiding magic and papering over the low-level libraries details—like the cache name and list of resources that `PrecacheManager` could expose—seems to be the *raison d'être* for `SWLib`, so I'm 👍  with your proposal. I don't know that we'd want to create a `PrecacheRoute` in that case, since the base `Route` class is sufficient to handle what we want.

We could move the `navigateFallback` discussion to a different issue.

**Comment by gauntface** [comment]
coolio and :+1: to moving navigateFallback to a seperate issue to track it.
