### ISSUE TITLE
gulp documentation runs out of memory

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#138]
The relevant bit is this: 

`ATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

The end of the console output is below. Note the first line.

[10:10:05] Finished 'documentation:projects' after 44 s

<--- Last few GCs --->

   87956 ms: Mark-sweep 1364.2 (1434.7) -> 1362.5 (1434.7) MB, 926.5 / 0.0 ms [allocation failure] [GC in old space requested].
   88878 ms: Mark-sweep 1362.5 (1434.7) -> 1362.4 (1434.7) MB, 921.8 / 0.0 ms [allocation failure] [GC in old space requested].
   89811 ms: Mark-sweep 1362.4 (1434.7) -> 1362.4 (1410.7) MB, 932.9 / 0.0 ms [last resort gc].
   90732 ms: Mark-sweep 1362.4 (1410.7) -> 1362.4 (1410.7) MB, 920.1 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x121b8a6cfb51 <JS Object>
    1: emit [events.js:~136] [pc=0x198642d24786] (this=0x205b916410a1 <a DestroyableTransform with map 0x21429a4e3a61>,type=0x121b8a6dd349 <String[4]: data>)
    2: arguments adaptor frame: 2->1
    3: flow [/Users/jmedley/Documents/tools/sw-helpers/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:~617] [pc=0x198642cd5e7f] (this=0x121b8a6e6ec1 <JS Global Object>,src=0x...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::LCodeGenBase::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/usr/local/bin/node]
 6: v8::internal::LChunk::Codegen() [/usr/local/bin/node]
 7: v8::internal::OptimizedCompileJob::GenerateCode() [/usr/local/bin/node]
 8: v8::internal::Compiler::FinalizeOptimizedCompileJob(v8::internal::OptimizedCompileJob*) [/usr/local/bin/node]
 9: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/usr/local/bin/node]
10: v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
11: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x198641e092a7
Abort trap: 6

**Comment by gauntface** [comment]
Just to clarify: this is using `gulp documentation`

**Comment by jeffposnick** [comment]
I'll file a PR to update the `documentation` dependency, which I'd been meaning to do anyway. Maybe it's resolved in a more recent release.

Also, @jpmedley, what does `node --version` say?

**Comment by jpmedley** [comment]
Upgraded to 7.4.0 and getting an identical message. 

This is on mac.

**Comment by jeffposnick** [comment]
I believe @gauntface fixed this with https://github.com/GoogleChrome/sw-helpers/pull/154
