### ISSUE TITLE
Add examples to all public methods.

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#139]
**Library Affected**:
*sw-precaching*

**Browser & Platform**:
*All browsers*

**Issue or Feature Request Description**:
A few of our public methods currently include a code snippet, but others reference the source implementation without providing one. If a public method is meant to be used, we could try to include a usage snippet so it's clear how to use it on it's own.

**Comment by addyosmani** [comment]
It would similarly be great if we could as much as possible make snippets complete. One example is the RevisionedCacheManager. We show examples of how to use an existing instance of RevisionedCacheManager but not how to create one or what the defaults for it are.

e.g https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-precaching#cache-1

**Comment by gauntface** [comment]
I've collapsed this in #164
