### ISSUE TITLE
npm install not installing some packages

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#143]
**Browser & Platform**:
Ubuntu/Linux

**Issue or Feature Request Description**:
Running `npm install` did not install two packages needed by `gulp documentation`. Specifically `gulp-sourcemaps` and `tmp`.

**Comment by jeffposnick** [comment]
Hmm, that's weird, as both of those are dependencies of other modules (`vinyl-fs` has `gulp-sourcemaps` as a dependency, and `selenium-webdriver` has `tmp` as a dependency), so they should have gotten picked up transitively as part of the `npm install`. That's what happened with me when I just tried it after blowing away my existing `node_modules/`.

But explicitly listing them as top-level dependencies is definitely a best practice. I can file a PR.

**Comment by jeffposnick** [comment]
Is there a reason you closed this, @jpmedley? It's still a problem, right?

The PR to fix it wasn't merged yet, and once it's merged, it would have auto-closed this issue.
