### ISSUE TITLE
sw-precaching ability to set cache name

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#145]
At the moment the precaching and runtime caching modules have got their own caches. Without really trying to cache in particular places I've ended up with 3 caches and it just looks / feels messy.

Is this ok? Should we consolidate to a single default cache? Is there any issues with that?

**Comment by jeffposnick** [comment]
Different caches for different purposes doesn't strike me as a problem. (I mean, the `sw-precache`'s old behavior was a mess, I know, but we're not talking about that...)

It's nice to be able to look at the top-level list of caches and make sure that you have multiple ones to confirm that both your precaching and runtime caching are behaving properly.

It's also a nice distinction to know that all the entries in a specific cache are managed via the same expiration policy, which wouldn't be the case if we mixed up precached and runtime cache entries.

**Comment by gauntface** [comment]
Moving to RequestWrapper should fix this.

**Comment by gauntface** [comment]
@jeffposnick @addyosmani 

I was considering how best to implement custom cachenames for the precaching.

Out of the box all of this works but does assume that precaching + warmRuntime cache are fine being in only two caches (i.e. assumes developers won't want to do something like):

```javascript
revisionedCacheManager.cache({
  revisionedUrls: [....]
  cacheName: 'images'
})

revisionedCacheManager.cache({
  revisionedUrls: [....]
  cacheName: 'styles'
})

revisionedCacheManager.cache({
  revisionedUrls: [....]
  cacheName: 'scripts'
})
```

This isn't infeasible to implement, just the current API prevents it.

There are a few options to support this:

1. Remove the precache-manager completely. All this class does is trigger the install and activate steps. It could be argued that this is useful in sw-lib, but less so for this low level module. Only loss from the current design is that developers of sw-precaching would need to implement the install and activate events on their own.
2. Expose the Revisioned and Unrevisioned CacheManagers as well as the PrecacheManager. Offers all the current APIs + exposes the raw managers. Downside is that this introduces questions as to when use the raw managers vs the precache manager.
2a. (Slight variant) Add a new method `addManager` to precacheManager, this will then loop through the managers and trigger the appropriate install and activate calls. (Offers little to the developer, but helps to prevent any bad practices and makes the raw managers feel natural to use).
3. Change precache manager to accept entries + cacheName and generate revisioned / unrevisioned cache managers per cache. Win of this is that easiest for developers (i.e. events are managed for them). Could lead to some messy situations when hooking this up with routes (which at the moment is done by exposing the raw mangers).

What do people think of this? I'm leaning towards 1 or 2a at the moment.

**Comment by jeffposnick** [comment]
Let's talk about this at the new sync up, as I've got to admit that I don't understand how all those classes fit together, and therefore find it hard to make an informed comment about the design.

**Comment by jeffposnick** [comment]
(The takeaway from the sync was that Matt is going to go with option 1.)
