### ISSUE TITLE
Empty Cache when incorrect cache name used

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#146]
I had set up for the following route:

```javascript
swlib.router.registerRoute(<Regex>, swlib.cacheOnly({
    cacheName: <Precache Cache Name>/
}));
```

The trailing slash on the cache name was added by accident but the result was a cache being created that was never used and once I fixed the problem, the cache persisted (i.e. wasn't cleaned up).

**Comment by jeffposnick** [comment]
Similar to the comment I made elsewhere, I'm hesitant to automatically delete/migrate things given that local development is done for multiple projects against a common origin (e.g. `localhost:8000`).

It can be dangerous to guess about whether something is leftover from a bad configuration vs. being used by a different web app deployed on the same origin.
