### ISSUE TITLE
Runtime Caching - Use Head request?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#147]
This might be a bad idea but with `StaleWhileRevalidate` runtime caching, could we make a HEAD request to check if the content had changed and if it has, then request the body and update the cache?

My main thinking here is that for images it would be helpful to have a runtime caching of them while also only updating them when needed.

**Comment by jeffposnick** [comment]
If the web server uses eTags and proper HTTP cache lifetimes, then the network request used to "revalidate" should already result in a body-less [HTTP 304 response](https://httpstatuses.com/304). So we'd effectively get the behavior you describe.

If the web server isn't properly setting HTTP caching headers, then maybe there's some value, but how likely is it that a server that isn't setting proper caching headers will be respond to a HEAD with meaningful information that could be used to determine freshness?

Also, I feel like if we did implement something to deal with that scenario, we'd have to really go all-in and end up rewriting the browser's HTTP cache validation logic inside the service worker, or else be *really* explicit about explaining how our implementation differs.

**Comment by gauntface** [comment]
Totally right, wasn't considering the HTTP cache doing it's part.
