### ISSUE TITLE
gulp documentation error

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#149]
This command:

`gulp documentation --project --sw-appcache-behavior`

Produced this result:

```
[12:30:46] Finished 'documentation:projects' after 44 s

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Input files must be buffered!
```

**Comment by jeffposnick** [comment]
The syntax you're looking for is `gulp documentation --project='sw-appcache-behavior'`, i.e. don't use `sw-appcache-behavior` as a flag, but rather use it as a value passed to the `--project` flag.

(I don't get that error when I run `gulp documentation --project --sw-appcache-behavior` locally, despite the incorrect flag usage.)

Taking a step back, though, I wonder how much time should be devoted to debugging issues with the existing automatic documentation generation, given that @gauntface has plans to switch it over to `npm-publish-scripts`? If/when that happens, the existing `gulp documentation` flow won't be relevant anymore.

**Comment by gauntface** [comment]
Yeah I'm looking into this now.

The gulp documentation task was actually failing because of the build task that was set as a dependency.

I'm going to shift the readme's around a bit and get the demo's up and running and will update this asap.
