### ISSUE TITLE
Route Docs - handler and match

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#150]
The Route docs don't explain what is passed into callbacks for match and handler.

match	function	
The function that determines whether the route matches.

handler	Object	
An Object with a handle method. That method will be used to respond to matching requests.

method	string (Optional)	
Only match requests that use this HTTP method. Defaults to 'GET' if not specified.

**Comment by jeffposnick** [comment]
I've got a PR coming up with revised JSDocs. I'll make sure to clarify that.
