### ISSUE TITLE
Make sure that ExpressRoute only matches same-origin requests

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#151]
Right now the `goog.routing.ExpessRoute` just looks at `.pathname` of the request URL, and compares it to the path used to the configure the route.

This means that a request for `https://cross-domain.com/path/to/file` would match a route that was configured with `new ExpressRoute({path: '/path/to/file', hander})`, even if the service worker were served from `https://example.com`.

I *think* the decision was made not to support that additional `origin` configuration option that `sw-toolbox` supported, and which was pretty confusing. (@gauntface @addyosmani, can you confirm that's what we decided?)

I'll point out in the docs that `ExpressRoute` should only be used for same-origin routing, and if cross-origin routes are needed, something like `RegExpRoute` is a better choice.

**Comment by gauntface** [comment]
This sounds good to me.

I was never a fan of the origin parameter in sw-toolbox and I feel that developers should be more cautious with third party requests so LGTM.
