### ISSUE TITLE
sw-background-sync-queue

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#16]
**Library Affected**:
sw-background-sync-queue

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
["One-shot" background sync](https://developers.google.com/web/updates/2015/12/background-sync?hl=en) has some common usage patterns that we might be able to automate—e.g., provide a method to coordinate passing data between the controlled page and the service worker (via `postMessage()` or `IndexedDB`) and a helper to automate the `sync` event handling in the service worker to consume that data from the queue of pending requests.

**Comment by addyosmani** [comment]
cc @marcacohen who had some ideas about an Outbox style library that could fit in here.

**Comment by prateekbh** [comment]
@addyosmani @jeffposnick 
trying to wrap my head around this, is it that we are trying to implement a queue kind of solution, to which all the request can be submitted and the specified 'sw-helper' can pick them keep firing them one after the other?

Do we have some use cases where we are trying to see this work, although I have worked on one such use case(where a QUEUE implementation is important), but would be really nice to know more?

**Comment by jeffposnick** [comment]
I don't think this one's gone beyond the "wouldn't it be cool if..." stage. But yes, "work queues" of one sort or another falls into the scope of what we're talking about.

I think the general idea is that this is an area where the underlying primitive (the `sync` event handler) is fairly low-level, and it benefits from being combined with other primitives (like IndexedDB) in order to solve general problems. Creating a library that handled that combination in an opinionated matter is within the scope of what we're trying to do with these projects.

**Comment by prateekbh** [comment]
Alright, so far based on some use cases I know (e.g. fb/twitter likes, passing coordinates from an uber like app where you like to track a delivery guy). I am guessing some stuff like below should work.

##js @ Controlled Page:
```html
<script src='../../pathToClientHelper.js'></script>
<script>
/*
 ###earlier code:
 if(navigator.onLine){
  fetch(requestObj).then(res=>res.json())=>(res=>{
    //do something with res
  });
 } else {
  //register bg sync and put stuff it in iDB or something
 }
*/

 //###new code
 //to make a req
 goog.bgQ.push(requestObj [,tagName]).then(taskId=>{
  // this task id can be used to see the status/response of req
 });
 
 // to fetch response of a taskId
 goog.bgQ.seek(taskId).then(taskResponse=>taskResponse.json()).then(res=>{
  if(res.isResponsefetched){
    console.log(res.response)
  }
  else{
    console.log("response not fetched yet");
  }
 });

 //also if a page is open it can listen to postMessage from sw as they happen. client.postMessage
</script>
```

**Comment by jeffposnick** [comment]
Hey @prateekbh: It's generally a good practice when using service workers to treat them as a progressive enhancement, and avoid changing the code in your client pages.

So rather than explicitly add in a helper library to client pages and have those pages behave differently depending on the state of `navigator.onLine`, the idea would be that a service worker could handle network failures as part of a `fetch` event handler, and inside that handler, implement the logic for queueing and subsequently retrying requests.

I don't even know if, in this model, there needs to be code in the client page to listen for a `message` event from the service worker indicating that the queue has been cleared. It may make more sense for the service worker to just show a notification when the queue's cleared, since the client page might have been closed in the interim.

Anyway, this is not currently at the top of our list to implement, but those are my general thoughts as to how it could be approached.

**Comment by addyosmani** [comment]
Caught up with @prateekbh today and it looks like we've got a good opportunity to get this knocked out :) We're going to get him added to our team sync and explore a design doc for this work.

**Comment by gauntface** [comment]
Can this be closed now that @prateekbh's work has landed?
