### ISSUE TITLE
Every Module Should Have a Demo.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#164]
This is a checklist of things missing from current docs.

- [ ] Every module has a demo.
    - [ ] Add some styles to demos.
    - [ ] Make it more evident as to what the demo is showing off.
- [x] Every module has a description for the module in JSDocs.
- [x] Every module has some JSDoc OR we have some markdown file introducing each project.
- [x] Add examples to every method.
- [x] Add Example of public constructor.
- [x] Add fuller examples on each index.

**Comment by gauntface** [comment]
cc @jpmedley I'll go through this with you sometime next week to get your thoughts / input on this as well as how to use [npm-publish-scripts](https://googlechrome.github.io/npm-publish-scripts/) (if you are interested).

**Comment by jpmedley** [comment]
"how to use npm-publish-scripts (if you are interested)." Never ask if I'm interested. Ask when I have the time.

**Comment by prateekbh** [comment]
@gauntface current JSDocs also $0 thingy, after every parameter. May be we can cover to remove them as well
e.g. https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-background-sync-queue#constructor

**Comment by gauntface** [comment]
@prateekbh what is the $0 thingy you are referring to?

**Comment by addyosmani** [comment]
I have an issue for migration docs tracked at #109 - should this be folded in here or best to keep that separate?

**Comment by gauntface** [comment]
@addyosmani Keep it seperate for now - I've change the title for this to just cover Demos.

**Comment by gauntface** [comment]
Going to close this - demo's still need some love, but can be done if and when we feel it's important
