### ISSUE TITLE
The 'try it out' link is broken on the sw-precaching readme.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#167]
**Library Affected**:
*sw-precaching*

**Browser & Platform**:
*n/a*

https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-precaching#demo

**Comment by jpmedley** [comment]
The 'demo directory' link is broken too.

**Comment by gauntface** [comment]
This is mentioned in #164
