### ISSUE TITLE
offline-google-analytics does not work with sendBeacon

### ISSUE THREAD

**Issue by igrigorik** [GoogleChrome/sw-helpers#19]
Couple of issues..

1. sendBeacon uses POST to transmit data
1. The URL is not unique ([current code assumes that it is](https://github.com/GoogleChrome/sw-helpers/blob/sw-offline-ga/projects/sw-offline-google-analytics/src/offline-google-analytics-import.js#L42)) and import needs to store and retransmit the POST payload.

To reproduce, enable sendBeacon transport in your GA config:

```
ga("set", "transport", "beacon");
ga("send", "pageview");
```

**Comment by jeffposnick** [comment]
Cool. Thanks for the details; I'll take a look!

**Comment by jeffposnick** [comment]
@philipwalton also let me know about another POST endpoint, [`/batch`](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#batch), with similar payload considerations.

**Comment by jeffposnick** [comment]
@igrigorik, I've added in what I hope should support beacon-based transport in https://github.com/GoogleChrome/sw-helpers/commit/5320c8269f3368939bf792c4bc1a47487ca7963f. Feel free to pull in that latest code and try again.

I'm still working on finding an effective way to automate testing at least some of the code, and am waiting on that before releasing this officially.

**Comment by igrigorik** [comment]
@jeffposnick thanks for working on this! Left a comment on the commit.. will take it out for a spin.

**Comment by jeffposnick** [comment]
This was fixed in the version that's been merged.
