### ISSUE TITLE
Include comment in generated SW file

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#195]
Feedback from @devnook: It would be a good idea to provide a comment at the top of the generated service worker file pointing to the relevant documentation, as well as pointing to an example of how to register the service worker from client pages.

C.f. the more draconian comment warning at https://github.com/GoogleChrome/sw-precache/blob/master/service-worker.tmpl#L17

**Comment by addyosmani** [comment]
This is something you get used to once you've used the generated SW for a while and I've definitely noticed folks trip up on it on occasion. I think including a comment is a great idea.

**Comment by gauntface** [comment]
@jeffposnick was there anything else you wanted beyond this: https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/templates/sw.js.tmpl#L4
