### ISSUE TITLE
Rename "behavior" to "plugin"

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#196]
Feedback from @devnook: the term "behavior" is a lot less common than "plugin". We should consider just adopting "plugin" throughout the project.

This has the advantage of kinda-sorta looking like how [Webpack supports extensibility](https://webpack.github.io/docs/using-plugins.html#built-in-plugins).

**Comment by gauntface** [comment]
I am :+1: this proposal, hadn't thought of it as a name before but definitely clicked with me.

**Comment by prateekbh** [comment]
Yes plz, makes way more sense...
