### ISSUE TITLE
SWLib Docs should show some usage plugins as well

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/sw-helpers#202]
**Library Affected**:
sw-lib

**Browser & Platform**:
All

**Issue or Feature Request Description**:
Doc enhancement

SWLib package brings a higher level framework kind of encapsulation for components from multiple packages(e.g. sw-runtime-caching). Although bringing all of the encapsulated package's documentation won't ever make sense, but I guess one feature that should be highlighted in the docs of SWLib is the way you add external plugins in handlers encapsulated in SWLib.

https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.7/module-sw-lib.html
^ URL does not currently highlight this thing. Doing so will ease the Dev's journey to plug and play responsive-image and background-sync queue plugins.

**Comment by gauntface** [comment]
Would this just require surfacing the example from "RuntimeStrategyOptions" from[ this page](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.7/module-sw-lib.SWLib.html#main) more prominently?

**Comment by prateekbh** [comment]
yeah,
Just making sure that devs would know very clearly that this lib is extensible with plugins as well.

**Comment by addyosmani** [comment]
Calling out that we have an external plugin story seems like an important high-level topic for the documentation. @prateekbh Is there anything more beyond surfacing the RSO example that you would suggest adding here to help make it clear we work well with plugins?

**Comment by prateekbh** [comment]
I guess I am missing something, 
https://github.com/prateekbh/Guess/blob/master/sw.js#L33
Here I am trying to add background-sync to my sw with `sw-lib` but it seems RequestWrapper is not exported from `sw-lib`.

Is there a way I add custom plugins into handlers of `sw-lib` ?

**Comment by gauntface** [comment]
Pings on hangouts but will put here. See `RuntimeStrategyOptions`: https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.7/module-sw-lib.SWLib.html#.RuntimeStrategyOptions
