### ISSUE TITLE
Joe Feedback - Delete console.log(self.goog.swlib) from examples

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#215]

**Comment by jpmedley** [comment]
"Joe Feedback"




Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by addyosmani** [comment]
Is this what Joe was referring to https://github.com/GoogleChrome/sw-helpers/blob/4a064d47b62b0e7bc361288f151560503e789d9d/packages/sw-lib/src/index.js#L37?

**Comment by gauntface** [comment]
yes I believe so.
