### ISSUE TITLE
Support for ES2015 module as output format of sw-build

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#222]
**Library Affected**:
`sw-build`

Right now, you can call `generateFileManifest()` on `sw-build` and get a file that, when imported, will set a `__file_manifest` global variable, based on [this template](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/templates/file-manifest.js.tmpl).

Unless @gauntface objects, I'll add in support for doing something similar, but with a ES2015 module format as the template, and a method name like `generateES2015FileManifest()`. (I could imagine that method name might be improved upon.)

**Comment by gauntface** [comment]
Maybe passing in a parameter to the function for `format: 'es2015'` would be a better approach?

**Comment by jeffposnick** [comment]
Sure, that would be cleaner. If I went that route then it might make sense to adopt the Rollup syntax for its [`format` option](https://github.com/rollup/rollup/wiki/JavaScript-API#format), and take in either `'iife'` or `'es'`.

Though I'd think in that case it should be a required parameter, instead of trying to default to one.

**Comment by gauntface** [comment]
I think having a default is fine, only request from me is that it be something that runs in the browser. +1 following rollups format option.

**Comment by jeffposnick** [comment]
Okay. Will do.

**Comment by jeffposnick** [comment]
This was fixed in https://github.com/GoogleChrome/sw-helpers/pull/225

**Comment by addyosmani** [comment]
> Sure, that would be cleaner. If I went that route then it might make sense to adopt the Rollup syntax for its format option, and take in either 'iife' or 'es'.

I like the idea of adopting Rollup's convention for formatting here. Consistency would also help devs reason about how to use this across different tools. 👍 from me!
