### ISSUE TITLE
Direct support for functions in Route({handler})

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#231]
**Library Affected**:
`sw-routing`

We currently require that when a `Route` is instantiated, the `{handler}` parameter passed to the constructor is an object that exposes a `handle` function, and that `handle` function is what's responsible for returning a `Promise<Response>`.

That works okay when you're using one of the handlers from `sw-runtime-caching` (like `StaleWhileRevalidate`, etc.), but when you just want to do something simple and provide your own function, it leads to awkwardly wrapping the `{handler}` value in an anonymous object with a `handle`, like so:

```js
const route = new goog.routing.RegExpRoute({
  regExp: new RegExp('^/article/'),
  handler: {handle: () => caches.match('app-shell.html')},
});
```

My initial motivation for this was to enforce consistency and reduce overloaded behavior (since the `sw-runtime-caching` classes all are objects which expose `handle` functions), but I'm starting to change my mind about whether it's a good idea.

How do folks feel about relaxing that restriction, and making it so that you could just pass in a function directly as the `{handler}` value? It would lead to code that looks like:

```js
const route = new goog.routing.RegExpRoute({
  regExp: new RegExp('^/article/'),
  handler: () => caches.match('app-shell.html'),
});
```

Right now we have an assertion that checks whether the `{handler}` value is an object that exposes a `handle` property, so we would also relax that and allow the value to be a `function` or an object with `handle` (to ensure we still support `sw-runtime-caching`).

**Comment by gauntface** [comment]
SGTM
