### ISSUE TITLE
Clarify how RegExp routing matches

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#237]
**Library Affected**:
`sw-routing`, `sw-lib`

There's been some confusion about how the RegExp is applied when matching against URLs for routing. The docs should be explicit that the match doesn't have to apply to the whole URL, and that the `new RegExp(string)` syntax tends to be cleaner when including URL paths, since otherwise the `/` characters need to be escaped.

E.g. if we wanted to match all requests made for any resource on https://example.com, like https://example.com/page1, https://example.com/page2, a good RegExp to use would be `new RegExp('^https://example.com/')`. This ensures that the match is made at the start of the URL (via the `^` character) and it's not necessary to include any sort of `.*` wildcard, since that RegExp will match both 'https://example.com/page1' and 'https://example.com/page2' as-is.

**Comment by addyosmani** [comment]
> The docs should be explicit that the match doesn't have to apply to the whole URL

My interpretation is that it would have to apply to the entirity of the URL so 👍 to being more clear on  what the exact behavior is.

**Comment by gauntface** [comment]
One thing to call out is that generic regular expressions could cause issues.

For example:

    /\/(.*\/)?.*\.(png|jpg|jpeg|gif)/

Would catch any image regardless of origin.

**Comment by jpmedley** [comment]
So this is valid? 

`RegExp('^https://example.com/')`

Out of curiosity, what other regex implementations behave like this?

**Comment by jeffposnick** [comment]
@jpmedley, `RegExp('^https://example.com/')` is a valid regular expression that will match any string which starts with `'https://example.com/`'. It could be useful within the context of routing if your goal is to match URLs that have that prefix.

> Out of curiosity, what other regex implementations behave like this?

I don't understand what you're asking here.

**Comment by jeffposnick** [comment]
I'm going to change the `RegExpRoute` behavior to match what seems to be the ideal behavior described at https://github.com/GoogleChrome/sw-helpers/issues/281#issuecomment-285130355

I'll include updates to the docs to reflect that behavior in the PR.

**Comment by jpmedley** [comment]
Cool.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*
