### ISSUE TITLE
sw-cli: investigate support for generate:foo pattern

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#243]
**Library Affected**:
sw-cli

**Browser & Platform**:
Google Chrome v51.0.1 for Android, or "all browsers"

**Issue or Feature Request Description**:
The CLI currently uses the `sw-cli generate-a`, `sw-cli generate-b` pattern. I propose we switch to `sw-cli generate:a`, `sw-cli generate:b`, which gives generation a namespace and might better support chaining in the future.

**Comment by gauntface** [comment]
I'm fine with this - at the moment the logic for the CLI is 

sw-cli <Command Name> <Options>

So we can change to `generate:sw` and `generate:manifest` if @addyosmani @jeffposnick are ok with that?
