### ISSUE TITLE
Deprecate sw-appcache-behavior

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#245]
**Library Affected**:
sw-appcache-behavior

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:

Looking through the usage of our libraries on BigQuery, I wasn't able to find more than 1 or 2 sites that tried to use the appcache-behavior. Because our AppCache story has always been about migrating users to SW rather than providing a fallback solution, I think the effort we provided here was useful but may not be worth rewriting for sw-lib.

My proposal is that we deprecate sw-appcache-behavior for the post-beta timeline (before I/O) and encourage folks to directly use Service Worker. 

Thoughts welcome @jeffposnick @gauntface et al

**Comment by jeffposnick** [comment]
The project's original goal was to ensure that if the time comes that App Cache support is removed from a given browser, there's a low-effort migration path to an equivalent service worker implementation.

Given that App Cache didn't have widespread adoption to begin with, and given that no browsers have ended support, I wouldn't expect there to be much usage right now (or, really a huge amount of usage, ever). But I do think we need to keep it around to provide a migration path for affected developers at some point in the future.

The service worker bit of the codebase follows similar patterns to what's used by the newer modules, and is analogous to the handlers in `sw-runtime-caching`, though the interface that's exposed isn't identical.

My vote would be to keep this around as part of the repo, and we can leave this issue open to track refreshing the interface to play nicely with the rest of the framework.

**Comment by jeffposnick** [comment]
`sw-appcache-behavior` has been moved to its own dedicated repo, so I'm closing the issue.

We may attempt to rewrite it and move it back into this repo at some point in the future.
