### ISSUE TITLE
Add networkTimeoutSeconds

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#246]
See: https://github.com/GoogleChrome/sw-toolbox/issues/221 for details

**Comment by jeffposnick** [comment]
This only makes sense when used with the `NetworkFirst` runtime handler, so I'll add it in there directly. (As opposed to adding in somewhere in the generic `RequestWrapper` interface.)

**Comment by gauntface** [comment]
It would be good to capture Mat's comment in a test (i.e. if we set timeout of 1 second and we have a cached response, make sure we get the cached response within a 2 seconds).
