### ISSUE TITLE
AppVeyor - Addy + Jeffy

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#247]
Get you both set up to administrate appveyor

**Comment by gauntface** [comment]
@addyosmani @jeffposnick I tried adding both of you to AppVeyor, did either of you receive anything about this?

**Comment by gauntface** [comment]
Addy is sorted out - now just Jeff.

**Comment by jeffposnick** [comment]
My account looks good, too! 👍
