### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#271]
**Library Affected**:
*sw-appcache-behavior*

**Browser & Platform**:
*"all browsers".*

**Issue or Feature Request Description**:
*The 'About' link in the README is broken. I think I've found the [canonical source of the link](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-appcache-behavior/package.json), but I don't know what the correct URL is.*

I just need someone to tell me where it is, and assign this ticket back to me.

**Comment by jpmedley** [comment]
Also
- sw-offline-google-analytic

**Comment by gauntface** [comment]
This has been fixed - the JSDocs needed rebuilding and pushing (Previously there were no docs for these modules because they were existing modules before we started working on sw-helpers).
