### ISSUE TITLE
Create Missing Demos for Libraries

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#272]
**Library Affected**:
* *sw-cli* (Probably doesn't need one, so remove the link.)
* *sw-lib*
* *sw-precaching*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:
*We need a demo for certain packages to provide an example for it's use and to be consistent with other tools in the library.*

**Comment by gauntface** [comment]
Not sure a demo for sw-cli makes sense - it's just a set of commands that would be run (same for sw-build. But sw-lib and sw-precaching could do with one yes.

**Comment by jpmedley** [comment]
Then the cli demo link should be removed.
