### ISSUE TITLE
Relax same-origin requirement for Express-style routes?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#281]
**Library Affected**:
*sw-routing*

In reviewing examples/docs from @gauntface and @jpmedley, I've seen a couple of uses of Express-style routes to attempt to match cross-origin requests. As of https://github.com/GoogleChrome/sw-helpers/issues/151, we will only match same-origin requests if someone provides an Express-style route, and we will throw a runtime error if you pass in a string that includes a full URL, begining with `'http'`.

Seeing the natural inclination of both of those folks to try to use the library in that way, though, makes me want to at least revisit that decision. Here are the options that I see:

1. Leave things as-is. Documentation along with the runtime assertions will hopefully make sure that folks know how to use Express-style routes, and they'll fall back to RegExp routes for cross-origin requests.
2. Open things up so that you can pass in a full URL as an Express-style route, but overload the routing logic—when you pass in a full URL, you perform matches against the entire incoming URL for both same- and cross-origin requests, but when you pass in a partial URL you only perform matches against same-origin requests. (This is similar to the situation we ended up with in `sw-toolbox`, except we triggered cross-origin matching based on the presence of a separate `{origin}` option.)
3. Open things up to accept full URLs, but don't use overloaded routing logic. Always match all routes, whether they were specified as partial or full URLs, against both same- and cross-origin requests.

The distinction between 2. and 3. is illustrated by considering the following route:

```js
swLib.router.registerRoute('/path/to/file', staleWhileRevalidate);
```

What if there were an incoming request for `https://cross-origin-domain.com/path/to/file`. Should that route match?

It wouldn't match if we went with option 2., and that's probably what the developer intends, but then we need to explain clearly how we use change our cross-domain matching restrictions depending on whether the input was a full or partial URL.

It would match if we went with option 3., but matching in this case is probably *not* what the developer intended. I'm mostly worried about these false positives when a developer specifies a route that has a very broad wildcard, like `/(.*)`, which would end up matching all requests, both same- and cross-origin.

**Comment by gauntface** [comment]
Please ignore - just leaving notes for myself to form an actual response.

// This does not work - express route / sw-lib quirk
```
goog.swlib.router.registerRoute('https://fonts.googleapis.com/css?family=Slabo+27px', ...);
```

**Comment by gauntface** [comment]
I just put together a silly test script to get an idea of what we *might* be doing behind the scenes.

```
const pathToRegExp = require('path-to-regexp');

const testURLs = [
  '/',
  'http://localhost:8080/',
  'http://cdn.example.com/',
  'https://cdn.example.com/',

  '/styles/example.css',
  'http://localhost:8080/styles/example.css',
  'http://cdn.example.com/styles/example.css',
  'https://cdn.example.com/styles/example.css',

  '/other/styles/example.css',
  'http://localhost:8080/other/styles/example.css',
  'http://cdn.example.com/other/styles/example.css',
  'https://cdn.example.com/other/styles/example.css',
];

const routes = [{
  type: 'Express',
  print: '/styles/*',
  regex: pathToRegExp('/styles/*'),
}, {
  type: 'Regex',
  print: /\/styles\/.*/,
  regex: /\/styles\/.*/,
}, {
  type: 'Express',
  print: 'http://localhost:8080/styles/*',
  regex: pathToRegExp('http://localhost:8080/styles/*'),
}, {
  type: 'Regex',
  print: /http:\/\/localhost:8080\/styles\/.*/,
  regex: /http:\/\/localhost:8080\/styles\/.*/,
}, {
  type: 'Express',
  print: 'http://cdn.example.com/styles/*',
  regex: pathToRegExp('http://cdn.example.com/styles/*'),
}, {
  type: 'Regex',
  print: /http:\/\/cdn.example.com\/styles\/.*/,
  regex: /http:\/\/cdn.example.com\/styles\/.*/,
}, {
  type: 'Express',
  print: 'https://cdn.example.com/styles/*',
  regex: pathToRegExp('https://cdn.example.com/styles/*'),
}, {
  type: 'Regex',
  print: /https:\/\/cdn.example.com\/styles\/.*/,
  regex: /https:\/\/cdn.example.com\/styles\/.*/,
}];

routes.forEach((route) => {
  console.log('');
  console.log('');

  console.log(`${route.type} Matched: '${route.print}'`);
  console.log('------------------------------');
  testURLs.forEach((testURL) => {
    const result = route.regex.exec(testURL);
    if (result) {
      console.log(' - ' + testURL);
    }
  });
})

console.log('');
console.log('');
```

The results from this:

```
$ node index.js


Express Matched: '/styles/*'
------------------------------
 - /styles/example.css


Regex Matched: '/\/styles\/.*/'
------------------------------
 - /styles/example.css
 - http://localhost:8080/styles/example.css
 - http://cdn.example.com/styles/example.css
 - https://cdn.example.com/styles/example.css
 - /other/styles/example.css
 - http://localhost:8080/other/styles/example.css
 - http://cdn.example.com/other/styles/example.css
 - https://cdn.example.com/other/styles/example.css


Express Matched: 'http://localhost:8080/styles/*'
------------------------------
 - http://localhost:8080/styles/example.css


Regex Matched: '/http:\/\/localhost:8080\/styles\/.*/'
------------------------------
 - http://localhost:8080/styles/example.css


Express Matched: 'http://cdn.example.com/styles/*'
------------------------------
 - http://cdn.example.com/styles/example.css


Regex Matched: '/http:\/\/cdn.example.com\/styles\/.*/'
------------------------------
 - http://cdn.example.com/styles/example.css


Express Matched: 'https://cdn.example.com/styles/*'
------------------------------
 - https://cdn.example.com/styles/example.css


Regex Matched: '/https:\/\/cdn.example.com\/styles\/.*/'
------------------------------
 - https://cdn.example.com/styles/example.css



```

**Comment by jeffposnick** [comment]
At our meeting we discussed using a boolean option to toggle whether a match was restricted to same-origin URLs. That's kind of like option 2., but substitutes the magical overloaded behavior of checking for a string starting with `'https'` with an explicit opt-in. It also removes the distinction between what RegExp routes and what Express-style routes match, which is probably a good idea given the confusion in #237 

Should we go with a toggle approach, defaulting to same-origin-only?

**Comment by gauntface** [comment]
I'm not sure why we need the boolean flag at all.

The above is what I'd expect by default for express, the only thing it misses is if you wanted /styles/* to match both local and remote URLS.

The Regular expression is the slight curve ball since it matches any url by default (i.e. /\/styles\/*/ would match local and remote) which I think might catch some folk out - but I haven't seen any issues raised with this.

**Comment by addyosmani** [comment]
> For me - I'd expect the express or regular expression routes to match only my origin by default, but I would like both to match external origins if I add enough information to match the entire URL.

I'm in favor of this and just ran into the need for lowering the friction to match origins as much as we can. I'd also say we perhaps don't need the boolean flag.
