### ISSUE TITLE
Pipe contents of README.hbs to docs/index.md

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#289]
Because sometimes duplication is useful.

@jeffposnick @addyosmani @gauntface

**Comment by gauntface** [comment]
I'm not 100% sold on this idea. We can format docs/index.md with CSS but the readme is just pure markdown - nothing fancy.

If you can propose content that fits both readme and index then makes sense.

**Comment by jpmedley** [comment]
The fact that one is called 'README' unfortunate, because it's orthogonal to what they actually do. Their functions are close enough that users will always have to check both to find the thing they're looking for. Might as well make them the same.
