### ISSUE TITLE
Message handler to trigger replaying queued Google Analytics requests

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#30]
**Library Affected**:
`sw-google-offline-analytics`

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
It could be useful to define a `message` event handler in the `ServiceWorkerGlobalScope` that listened for requests from controlled pages to replay the Google Analytics hits, instead of only replaying them when the service worker starts up. This would allow, e.g., the controlled page to listen to [`window.online`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) and then tell the service worker to attempt replaying.

(This isn't fool-proof, due to [lie-fi](https://developers.google.com/web/fundamentals/performance/poor-connectivity/lie-fi?hl=en), but it's something people could opt-into.)

CC: @igrigorik

**Comment by igrigorik** [comment]
👍

**Comment by jeffposnick** [comment]
We're more likely to go with a rewrite based on https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-background-sync-queue than to modify the existing codebase, so I'm going to close this.
