### ISSUE TITLE
No support for setDefaultHandler/setCatchHandler in sw-lib

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#302]
**Library Affected**:
*sw-lib*

You can set a default handler that will be applied to all requests that aren't explicitly matched by other routes via [`Router.setDefaultHandler()`](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-routing/src/lib/router.js#L63).

You can't do that when you use the higher-level `sw-lib`'s wrapper on top of `Router`.

Ditto for `Router.setDefaultHandler()` not being exposed.

**Comment by gauntface** [comment]
This is fixed now in master and will be in the next release.
