### ISSUE TITLE
BroadcastCacheUpdates configuration for swlib.precache()

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#309]
**Library Affected**:
*sw-lib*

It's not currently possible to pass through configuration for the underlying `RequestWrapper` when using `swLib.precache()`. It would be nice to take that in as an optional second parameter.

The specific use case that I had in mind was being able to configure `sw-broadcast-cache-updates` so that you can be notified when a precached resource (like your App Shell HTML) gets updated.

(Not blocking for the hackathon, obviously, but just a nice-to-have that I wanted to track.)

**Comment by jeffposnick** [comment]
In thinking more about this, the only plugin that developers would likely find useful in `precache()`'s underlying handler is `sw-broadcast-cache-updates`.

We've also moved to a model where `sw-build` can be used to search a source file for instances of the string `precache([])` and injects a manifest, which doesn't fit cleanly with this proposed `precache([], requestWrapperOptions)` usage. (We could, of course, modify that replacement logic, or take in the configuration via the `SWLib` constructor.)

To float an alternate proposal, what do folks think about unconditionally enabling the `sw-broadcast-cache-updates` plugin within `precache()`'s underlying handler along with a reasonable default channel name, like `'precache-updates'`? Broadcasting occasional messages by default doesn't strike me as a problem, and it might be easier to come up with patterns for clients listening to the messages if we could assume it's always enabled with a well-known channel name.

**Comment by gauntface** [comment]
Generally pro this, could would like to be able to configure the name and be able to disable it from sw-lib constructor.

**Comment by jeffposnick** [comment]
Okay, we can treat it in the same way we treat the [proposed](https://github.com/GoogleChrome/sw-helpers/pull/445/files#diff-7b63578668d6d334559401feac159a5eR53) `directoryIndex` parameter in the `SWLib()` constructor—a default value that could be overridden if a valid string is passed in, or turned off entirely if a false-y value is passed in.

**Comment by gauntface** [comment]
I copied the sw-precache definition of falsey for directoryIndex 'false or null'.
