### ISSUE TITLE
Update sw-cli docs to use sw-cli generate:sw instead of generate-sw

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#314]
**Library Affected**:
sw-cli

Small one. Noticed we currently tell folks to use the older form of the command.
https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.8/module-sw-cli.html

**Comment by gauntface** [comment]
I've fixed up the doc site - this was a bug where old modules were still being including in documentation (the sw-cli is has no more reference docs and hasn't for some time).
