### ISSUE TITLE
sw-cli: consider explaining why saving to a config file is useful

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#315]
**Library Affected**:
sw-cli

Users might find it useful to understand why saving to a config file is a good idea:
![image](https://cloud.githubusercontent.com/assets/110953/23895624/81affca4-08fa-11e7-8688-76175ed70539.png)

**Comment by samthor** [comment]
My 2c: this config file is also saved minified, yet it might be useful to manually modify.

(because e.g. you have `globIgnore`, but don't expose this to users).

**Comment by jpmedley** [comment]
Scenario I tried:

1. Create `app/index.html`. 
2. Run cli and save to a config file.
3. Create `app/message.html` and `app/app.css`.
4. Rerun cli.

The second time around, message gets picked up, css does NOT. I would need to delete the config file before rerunning the cli. 

**Is this working as intended? or should step 4 pick up the css as well?**

**Comment by gauntface** [comment]
What would you like the behavior to be @jpmedley ?

**Comment by jpmedley** [comment]
@gauntface I took a second look and realized something I missed. Comment withdrawn.

**Comment by jpmedley** [comment]
Also pull request.

**Comment by jpmedley** [comment]
Does the PR work for everybody? Can we close this?
