### ISSUE TITLE
registerNavigationRoute() should default to looking in the precaching cache

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#321]
**Library Affected**:
*sw-lib*

https://github.com/GoogleChrome/sw-helpers/pull/307 added support for `swLib.registerNavigationRoute()`, and it uses `caches.match(url)` under the hood to return the response. It would make sense to change that to default to `caches.match(url, {cacheName})`, where `cacheName` defaults to `this._revisionedCacheManager.getCacheName()` but can be changed via an option if the developer wants something else.

It's not crucial for the hackathon, but it can work around an issue when upgrading from `sw-precache`, when there might still be an older entry with the same URL in one of the caches that `sw-precache` had created.

**Comment by addyosmani** [comment]
Adding to the hackday label. I ran into this last night when trying to use `registerNavigationRoute()` but it's great that you've already been thinking about modifying the behavior to look in the precaching cache.

**Comment by jeffposnick** [comment]
Yup, the default would be to look explicitly in `this._revisionedCacheManager.getCacheName()`, which is the cache used for precached assets.

But we'd also want to allow for overriding that default if a developer needs to.

**Comment by gauntface** [comment]
Why is caches.matches bad?

**Comment by jeffposnick** [comment]
In practice, I ran into issues when updating a site that previously used `sw-precache` and moved to `sw-helpers`. The `caches.match()` kept returning the response from the cache that `sw-precache` had created, because it will just return the first thing it finds.

Being specific by letting folks specify a cache name and defaulting to the most likely choice works around that, and it seems like a better approach in general.

**Comment by gauntface** [comment]
Understood. So what happens if I were to lazy cache paths in the runtime cache? That won't ever be used for navigation routes if we only look in the precache cache right?

**Comment by jeffposnick** [comment]
In that case, the developer would need to set the `cacheName` option to override the default.

I don't know that what you describe a use case we particularly want to encourage, but it's possible.

**Comment by gauntface** [comment]
The scenario where this would be desirable would be jakes wikipedia example where you cache pages for offline use. But it's an advanced example.

**Comment by jeffposnick** [comment]
I might be missing some nuance of Jake's example, but I think in that case, a route that just did traditional runtime caching would be fine. Such a route wouldn't explicitly check for `request.mode === 'navigate'`, but it could still match the URLs that are being navigated to.

Or if you wanted to use `NavigationRoute` in that scenario, you could, and just pass in an appropriate `cacheName`.
