### ISSUE TITLE
It is hard to find which caching strategies are available

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/sw-helpers#324]
**Library Affected**:
sw-lib

**Issue or Feature Request Description**:
The intro doc on sw-helpers (https://googlechrome.github.io/sw-helpers/) link to caching strategies in offline cookbook (https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/). But there is no 1:1 mapping between sw-lib strategies and that article. I fund a list of strategies in sw-lib doc, but they are mixed with other instance methods. It would be good to separate the strategies into their own namespace and link to that in the documentation.

**Comment by addyosmani** [comment]
I fully agree we should do a better job of highlighting supported caching strategies and the docs should also explain the differences in terminology from the sw-precache/sw-toolbox work and the newer stuff.

sw-toolbox had the following caching strategies:

![image](https://cloud.githubusercontent.com/assets/110953/23928496/2cabf030-0974-11e7-850d-ec947102decd.png)

You can find what is currently supported in sw-helpers here:
https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-runtime-caching.html

We could do a better job of mapping to https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#serving-suggestions in the way we present this information.

**Comment by jpmedley** [comment]
Either you need to change the names of your strategies to match Jake, or we need to rewrite Jake's article to use your names. Just let me know.

**Comment by gauntface** [comment]
swlib.strategies <- is the grouping for the strategies, so closing this.
