### ISSUE TITLE
sw-cli is missing 'glob' dependency

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/sw-helpers#325]
**Library Affected**:
sw-cli

**Browser & Platform**:
node v7.7.2

**Issue or Feature Request Description**:
clean install (`npm install sw-cli`), and running `sw-cli` script can't find glob module

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

`Error: Cannot find module 'glob'`

**Comment by addyosmani** [comment]
Verified:

![image](https://cloud.githubusercontent.com/assets/110953/23928699/55aac83e-0975-11e7-9225-029c26283ce0.png)

I think this may have slipped through the cracks as the monorepo's root package.json has the dependency in there.

**Comment by gauntface** [comment]
Added a test to both sw-build and sw-cli to prevent this from happening in the future - tests were using the project level dependencies meaning the published versions fell over.
