### ISSUE TITLE
Is webpack supported out of the box?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#327]
From Eric B. (Like a Boss)

**Comment by gauntface** [comment]
Current site is using alternative plugins.

**Comment by addyosmani** [comment]
Let's talk to @goldhand about his interest in Webpack plugins for the newer sw-build/sw-lib work. I know @prateekbh has also signified he'd be interested in looking at a WP plugin too.

**Comment by goldhand** [comment]
Would it be better to discuss this here or in #269 ?

One thought: currently the `swBuild` methods don't allow any options for handling the generated service worker as a string (before it is written to a file). It would be nice to be able to pass it as a string to webpack's `compiler`. Is there another way to use the string value for the generated serviceworker / manifest?

**Comment by addyosmani** [comment]
I think we should defer discussion to #269 and we'll close this as a dupe.
