### ISSUE TITLE
sw-cli docs include sw-build methods

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/sw-helpers#330]
**Library Affected**:
*sw-cli*

**Issue or Feature Request Description**:

The nodejs API documentation for `sw-cli` is incorrect. It looks like it's describing the API methods that are actually on `sw-build`
https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.8/module-sw-cli.html

**Comment by addyosmani** [comment]
Thanks for filing, @philipwalton. @gauntface Told Phil to move ahead with sw-build and sw-lib.

**Comment by jpmedley** [comment]
I think the documentation just needs to be redeployed. The source for this file is gone already. (@gauntface)

**Comment by addyosmani** [comment]
@gauntface were the docs redeployed since the hackathon?

**Comment by jpmedley** [comment]
I can find neither the source, nor evidence that this is autogenerated. Can someone point me in the right direction?

**Comment by gauntface** [comment]
look in package.json and you'll run the tasks you can run - specifically: 'npm run publish-gh-pages'

**Comment by gauntface** [comment]
I think this is more of an issue that the sw-cli file is no longer an actual node module and the old docs need deleting.
