### ISSUE TITLE
generate-sw -> generate:sw in sw-cli documentation

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/sw-helpers#333]
**Library Affected**:
*sw-cli*

**Issue or Feature Request Description**:
In sw-cli documentation (https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.8/module-sw-cli.html):
 s/generate-sw/generate:sw

**Comment by addyosmani** [comment]
Thanks for filing this, @devnook! Came across this last night and filed https://github.com/GoogleChrome/sw-helpers/issues/314 :) Going to close as dupe but we should definitely fix.
