### ISSUE TITLE
sw-build: globPatterns doesn't respect rootDirectory

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#338]
**Library Affected**:
sw-build

**Browser & Platform**:
All browsers

**Issue or Feature Request Description**:
Reported via @arthurevans: when specifying a `globPattern`, users expect that they won't need to define the `rootDirectory` as part of the `globPattern` path - it should be the prefixed used. The current behavior will however not work. To fix that you need to manually prefix the root directory yourself:

```diff
swBuild.generateFileManifest({
  dest: './dist/precache-manifest.js',
  rootDirectory: './dist/',
-  globPatterns: ['dist/**'],
+  globPatterns: ['dist/**'],
  globIgnores: ['service-worker.js'],
})
.then(() => {
  console.log('File manifest has been created.');
});
```

I have verified this locally and ran into this bug in my own implementation over in ReactHN.

**Comment by jeffposnick** [comment]
Related: https://github.com/GoogleChrome/sw-helpers/issues/358

**Comment by gauntface** [comment]
This should be fixed by https://github.com/GoogleChrome/sw-helpers/pull/408
