### ISSUE TITLE
sw-build: Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/sw-helpers#340]
**Library Affected**:
sw-build

**Browser & Platform**:
Node v7.7.2, Yarn v0.21.3

**Issue or Feature Request Description**:
When I run `require('sw-build')`, I get error: `Error: Cannot find module 'chalk'`

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by addyosmani** [comment]
I just created a new project, cleared the global cache and tried to install and call `generateFileManifest` from sw-build. I wasn't able to repro the chalk issue, but will take another look at it shortly. Thanks for continuing to file feedback, @samthor!

**Comment by gauntface** [comment]
I reproduced

1. create a new project
1. npm init
1. npm install sw-build
1. Make example js file that uses sw-build
1. Run file and notice errors

I've raised a PR to fix this BUT we need a way to test this in the future.....
