### ISSUE TITLE
Links on Getting Started page for sw-cli and sw-lib

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/sw-helpers#342]
The links to 'Learn More About ...' on the [Getting Started page](https://googlechrome.github.io/sw-helpers/getting-started/#main) might be better off pointing to the Using sw-cli and Using sw-lib pages.

**Comment by addyosmani** [comment]
I agree. @gauntface @jeffposnick wdyt?

**Comment by jpmedley** [comment]
The links in question are no longer there. The current landing page has links to the pages Sam suggests. https://googlechrome.github.io/sw-helpers/#main

Closing
