### ISSUE TITLE
mention in sw-lib docs that importScripts assumes using a build pipeline

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/sw-helpers#343]
**Library Affected**:
sw-lib

**Browser & Platform**:
all

**Issue or Feature Request Description**:
The docs say to use sw-lib like this:

```
importScripts('/node_modules/sw-lib/build/sw-lib.min.js');
goog.swlib.cacheRevisionedAssets([
  '/imgs/doit.1.jpg'
]);
```

I think this assumes that you're going to use a build pipeline to inline `sw-lib.min.js` into your service worker script. The docs should mention this.

I'm personally just hacking from scratch, without a build pipeline. When I try to run this offline, I get `an unknown error occurred when fetching the script` on the `importScript` line.  So, I assume that `sw-lib.min.js` isn't being cached and the service worker is getting an error when it tries to import it

**Comment by jpmedley** [comment]
You need to copy the *min.js and a few other files. https://googlechrome.github.io/sw-helpers/getting-started/sw-lib.html#install

**Comment by kaycebasques** [comment]
Nevermind, I think it's a bug in Canary
