### ISSUE TITLE
fix sw-cli install / command instructions

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/sw-helpers#344]
**Library Affected**:
sw-cli

**Browser & Platform**:
all

**Issue or Feature Request Description**:
[readme](https://github.com/GoogleChrome/sw-helpers#sw-cli) says to install sw-cli as a dev dep:

    npm install --save-dev sw-cli

and then the [sw-cli doc](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.8/module-sw-cli.html) assumes that you can run it as a global command

    sw-cli generate-sw

Either switch the readme to instruct to install it globally or change the command to use the local dev dep (e.g. `node_modules/.bin/sw-cli generate-sw`) 

I'm also getting an error that I need to install `glob` globally. Add it explicitly as a dependency of sw-cli?

**Comment by jpmedley** [comment]
This is blocked by https://github.com/GoogleChrome/sw-helpers/issues/349
