### ISSUE TITLE
Document that sw-lib can't be used uglify + Provide presets

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/sw-helpers#352]
**Library Affected**:
*sw-lib*, but probably all

**Platform**:
Using webpack 2.2.0

**Why do I care?** 
I'm already using webpack to bundle the rest of my site and want to include a piece of logic in my service worker that might be shared elsewhere without resorting to `importScripts` and leveraging existing webpack bundling.

**Description**
I know there's #269, but I would expect to still be able to require sw-lib without having to whitelist it from uglify (adding it to babel-loader can get it to work, but that increases build by ~30 seconds and needs a lot of presets) :)

in sw.js
```js
import swlib from 'sw-lib' // yields first error
import swlib from 'sw-lib/build/sw-lib.min.js' // yields second error
import swlib from 'sw-lib/build/sw-lib.js' // yields third error
swlib.warmRuntimeCache(['myfile.html'])
```

**Errors**
```
ERROR in sw.js from UglifyJs
Unexpected token: name (ErrorFactory$1) [./~/sw-lib/build/sw-lib.min.mjs:15,0][sw.js:90,6]
```

```
ERROR in sw.js from UglifyJs
Unexpected character '`' [./~/sw-lib/build/sw-lib.min.js:15,354][sw.js:88,339]
```

```
ERROR in sw.js from UglifyJs
Unexpected token: name (ErrorFactory$1) [./~/sw-lib/build/sw-lib.js:40,0][sw.js:113,6]
```

**Comment by gauntface** [comment]
@addyosmani @jeffposnick any ideas on what the problem is here?

**Comment by jeffposnick** [comment]
`uglify` doesn't grok ES2015 syntax, right? That's why we're using `babili`.

Transpiling down to ES5 syntax prior to running it through `uglify` (which @patrickhulce didn't want to do, since it increases build time), or alternatively using `babili`, would be the recommendation. The other solution would be for us to ship bundles that are pre-transpiled to ES5, but that seems like overhead, since we can guarantee ES2015 support in browsers that have service workers.

It's a common problem for anything using ES2015, so I'm not sure if it warrants special attention in our docs.

**Comment by gauntface** [comment]
So is there anything we want to do here close as an unsupported feature?

**Comment by jeffposnick** [comment]
My vote would be close as an issue outside the scope of this repo, but I'll let @patrickhulce weigh in.

**Comment by patrickhulce** [comment]
> since we can guarantee ES2015 support in browsers that have service workers.

Yeah this hits the nail on the head for why I suspected it was never considered, but I brought it up since it's the first thing I tried to do as a drop-in replacement for my existing service workers. If there's any space in documentation dedicated to "getting sw-lib integrated with build system X" then I think it's worth a line about which presets are needed and a pointer toward the babili preset. I'm fine for this issue to morph into tracking that documentation.

**Comment by gauntface** [comment]
Sounds good - renamed the issue.

**Comment by jpmedley** [comment]
@gauntface @jeffposnick 
I think the note I need to add isn't that 'Workbox doesn't work with uglyfy'. What I really need to say is 'your minifier needs to be ES6 aware.' I don't know if I should mention any specific minifier.

**Comment by gauntface** [comment]
baili is the only es2015 minifier I'm aware of - I don't think anything else exists.

**Comment by jpmedley** [comment]
Something just occurred to me. Workbox ships with a minified version of sw-lib. Are any minifiers able to minify a service worker while skipping their imports. I con't know if you can mix ES6 and legacy like that, but partial minification would solve the problem. (Surely this is a use case that comes up from time to time.)

**Comment by lencioni** [comment]
@gauntface I believe that [uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony) and [butternut](https://github.com/Rich-Harris/butternut) support ES2015 now too.

**Comment by jeffposnick** [comment]
See https://github.com/GoogleChrome/workbox/issues/523#issuecomment-305299222—only `babili` is bug-free and understands `async`/`await` as of right now.
