### ISSUE TITLE
Clarify that developers shouldn't hardcode the manifest

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#355]
**Library Affected**:
*sw-lib*

The https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-lib.html#main docs page has the following example:

```js
// Caching assets and registering routes.
goog.swlib.cacheRevisionedAssets([
  {
    url: '/',
    revision: '1234'
  },
  {
    url: '/styles/main.css',
    revision: 'abcd'
  }
]);
```

Reading this page gave @kaycebasques the impression that you should hardcode the manifest array and update the `revision` details by hand, when in fact we want people to use `sw-build` to generate that information. We should update the docs to make it clear that the manifest array should be generated as part of a build process.

**Comment by patrickhulce** [comment]
FWIW I still really appreciated it showing me the format it expects :) useful for those early and building an adapter for their own toolchain since it's basically just filename and hash
