### ISSUE TITLE
rootDirectory option is slightly confusing

### ISSUE THREAD

**Issue by pbakaus** [GoogleChrome/sw-helpers#357]
**Library Affected**:
sw-build

**Browser & Platform**:
*E.g. Google Chrome v51.0.1 for Android, or "all browsers".*

**Issue or Feature Request Description**:
Consider renaming the rootDirectory option to something like serverRoot, as I tried to bang my head why the glob didn't take it into account :)

**Comment by jeffposnick** [comment]
It's now `globDirectory`, FWIW: https://github.com/GoogleChrome/sw-helpers/pull/459

The idea being that it's the directory used as a the base for all glob patterns, which is also intended to be the same as the web server's root directory.

Do you feel comfortable with closing this issue, @pbakaus?

**Comment by pbakaus** [comment]
Yep! Thanks.
