### ISSUE TITLE
generateSW code example missing `dest` property

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/sw-helpers#359]
**Library Affected**:
sw-build

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:

Running this code from [examples](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-build.html#examples)

```
swBuild.generateSW({
  rootDirectory: './build/',
  globPatterns: ['**\/*.{html,js,css}'],
  globIgnores: ['admin.html'],
  serviceWorkerName: 'sw.js'
})
.then(() => {
  console.log('Service worker generated.');
});
```

yields `Error: The 'dest' value must be a valid path.`

**Comment by gauntface** [comment]
I believe this is fixed now in the docs.
