### ISSUE TITLE
sw-cli generate command docs doesn't match valid options

### ISSUE THREAD

**Issue by StephenFluin** [GoogleChrome/sw-helpers#362]
**Library Affected**:
sw-cli

**Browser & Platform**:
sw-cli 0.0.17

**Issue or Feature Request Description**:
The documentation [here](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.8/module-sw-cli.html) tells me to use `sw-cli generate-sw`, but it looks like from the command help that the command should be `generate:sw`.

```
$ ../node_modules/.bin/sw-cli generate-sw
Invlaid command given 'generate-sw'
stephenfluin-macbookpro:dist stephenfluin$ ../node_modules/.bin/sw-cli
sw-cli

Usage:
    sw-cli [command] [options]

Commands:

    generate:sw
    generate:manifest

Options

    -h --help               Show this help text.
    -v --version            Show current version of sw-cli

```

**Comment by jpmedley** [comment]
Duplicate (more or less) of https://github.com/GoogleChrome/sw-helpers/issues/330
