### ISSUE TITLE
Less-than-helpful sample code for cacheableResponse

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#363]
In https://googlechrome.github.io/sw-helpers/advanced/#main, there's an example that looks like:

```js
const cdnCacheStrategy = goog.swlib.staleWhileRevalidate({
  cacheableResponse: {
    statuses: [0],
  },
});
```

This would be more helpful for the copy-and-paste scenario if it used `statuses: [0, 200]`, just so that it won't fail to cache 200 response statuses in addition to 0 statuses.

CC: @philipwalton, who ran into this.

**Comment by jpmedley** [comment]
The example lives [here now](https://googlechrome.github.io/sw-helpers/recipes/cdn-caching.html#main).
