### ISSUE TITLE
sw-appcache-behavior bad function results in fail in *just* Firefox Stable

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#376]
**Library Affected**:
sw-appcache-behavior

**Browser & Platform**:
FF Stable

**Issue or Feature Request Description**:
When working on https://github.com/GoogleChrome/sw-helpers/pull/375 I had a bad function call to `logHelpers.log` as I renamed it to `logHelpers.info`.

This results in an error in the browser console - function doesn't exist.

In other browsers, the tests were passing, whereas Firefox Stable was failing to pass the tests. This may be an issue if the other browsers weren't actually passing the tests correctly, OR it could simply be that only Firefox stable has an issue with failing tests.

cc @jeffposnick

**Comment by addyosmani** [comment]
I think we mentioned this elsewhere but was there any concern with deprecating and moving this behavior out to another repo vs continuing to land fixes for it? (Jeff seems fine with updating but just wanted to sanity check)

**Comment by gauntface** [comment]
Personally, I'd favor moving to a seperate repo. Not kill it though if it still has use.

**Comment by addyosmani** [comment]
It hasn't seen a great amount of usage out in the wild from what I can see. As @jeffposnick is the owner, I'll defer to him: my suggestion is we move to a separate repo to keep focus on the newer libraries / work that will be ported but for now not deprecate/kill until clear no one is using it. Is that fair?

**Comment by jeffposnick** [comment]
No longer relevant as `sw-appcache-behavior` has been moved.
