### ISSUE TITLE
sw-build breaks without globIgnores

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/sw-helpers#389]
**Library Affected**:
sw-build

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:
I am not sure if this is a legit real world use case, but just while trying sw-build. 
I did not pass globIgnores in the config and it fell apart with the error 
*"Cannot read property 'push' of undefined"*
Code: https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/generate-sw.js#L69

P.S. Assign it to me if this is valid and you want a PR

**Comment by gauntface** [comment]
I raised a PR to fix this - just because I wanted to add some additional tests - found a reasonable gap in tests ;)
