### ISSUE TITLE
Insert Contents of Project-README into Package Index Files

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#393]
**Background**
The IA for this project has, among other items:

_Getting Started_
- _sw-build_
- _sw-cli_
- _sw-lib_

_Advanced_
- _etc. ..._

The consensus of the group seems to be that priority both in work and presentation be _sw-build_ and _sw-cli_, followed by other issues; and items under _Advanced_ to be downplayed. 

**Proposal**
The proposal is to:
1.  Include the package source files contents currently generated by [Project-README.hbs](https://github.com/GoogleChrome/sw-helpers/blob/master/templates/Project-README.hbs). This would basically put this content on the top-page for the modules they belong to (a [page like this](https://googlechrome.github.io/sw-helpers/reference-docs/stable/0.0.17/module-sw-precaching.html#main), for example.).
2. Remove them from the [github landing](https://googlechrome.github.io/sw-helpers/#main) page.

**Implementation**
Two possible ways:
* Automate it.
* Build it by hand.

I would like input and comments before I proceed.

**Comment by jpmedley** [comment]
@gauntface @jeffposnick

**Comment by gauntface** [comment]
The github landing page was altered to what you asked for originally where you wanted the Github Readme to be the same for the github pages index.

Whatever you think is best I'm down for.

+1 this suggestion.

**Comment by jpmedley** [comment]
That was before the IA. This suggestion wouldn't have made sense then.
