### ISSUE TITLE
generateFileManifest() starting from project root instead of app.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#403]
**Library Affected**:
sw-build*

**Issue or Feature Request Description**:
My code looks right, according to Matt. It is constructing a manifest.js from my project root instead of from my `app` directory. To run the faulty code, clone [from this branch](https://github.com/jpmedley/redder2/tree/sw-build) and run `gulp build` (which will run the faulty code).

The output from this looks normal:

    [09:09:52] Using gulpfile ~/Documents/projects/redder2/gulpfile.js
    [09:09:52] Starting 'build'...
    [09:09:52] Starting 'clean'...
    Build file has been created.

**Comment by gauntface** [comment]
Needed to test demo correctly:
```
npm install --save del jsdom 
```

Testing the input parameters, it ends up being:

```
{
  rootDirectory: './app/',
  dest: './app//js/manifest.js',
  globPatterns: [ '**/*.{html,js,css}' ]
}
```

Weird that the double '/' gets worked out.

The final output includes paths such as:

```
{
    "url": "/../builder.js",
    "revision": "1c1e1f15b85abbd6b1afbabfa2b3f098"
  },
  {
    "url": "/../gulpfile.js",
    "revision": "5f4b0b37d5d2cfee83eb2fa16331066e"
  },
```

**Comment by jpmedley** [comment]
The reason for './app/' is that I tried all the variations I could think of on what my rootDirectory should be and that happens to be the last one I tried. I get the same result with './app'.

**Comment by gauntface** [comment]
yeah I'm just stating what I found - the last bit if a bug - fixed it - just adding tests.
