### ISSUE TITLE
Formalize the manifest injection across sw-cli, Webpack, etc.

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#405]
**Library Affected**:
*sw-cli, sw-build, Webpack plugin?*

Some developers will use build tools that work best when the revisioned manifest is directly injected into a source `service-worker.js` file. (Others might want to use build tools to generate a standalone manifest that gets pulled in via `importScripts()`, and that's outside the scope of this issue.)

Injecting into a source file presupposes that our tools know *where* to inject, and after some discussion, we seem to have settled on checking for the presence of `cacheRevisionedAssets([])`, and then handle injection by replacing the `[]` with the populated manifest. If `cacheRevisionedAssets([])` can't be found in the source, it would be a fatal error.

While we were previously thinking about baking this logic into the forthcoming Webpack plugin, this behavior will be useful for users of the other build tools, like `sw-cli`, so it might make sense to implement it inside of `sw-build`.

CC: @prateekbh @gauntface

**Comment by gauntface** [comment]
Once this lands: https://github.com/GoogleChrome/sw-helpers/pull/408

I'd like to tackle this as it sounds like a good entry point to find more bugs like Joe's and get feedback ;)

**Comment by gauntface** [comment]
Thinking on this a little more.

There are a few options:

1. Read in file from `app/sw.js` (<root directory>/<service worker name>) and inject and output to `dist/sw.js` (<dest directory>/<service worker name>).
2. Take in a string, inject and return string (i.e. get the developer to manage the file manipulation).

#### Option 1
```javascript
swBuild.injectManifest({
  dest: './build/'
  rootDirectory: './app/',
  staticFileGlobs: ['**\/*.{html,js,css}'],
  globIgnores: ['admin.html'],
  swFile: 'sw.js'
})
.then(() => {
  // File read from `./app/sw.js` and written to `./build/sw.js`
});
```

#### Option 2
```javascript
swBuild.injectManifest({
  rootDirectory: './app/',
  staticFileGlobs: ['**\/*.{html,js,css}'],
  globIgnores: ['admin.html'],
  swString: 'goog.swlib.cacheRevisionedAssets([]); // Do something cool here.'
})
.then((swStringWithManifest) => {
  // Manifest injected directly into `swString` and returned in promise
});
```

I can see a use case for both.

1. (Manipulation of files directly) is super friendly for developers that aren't using a supported build process.
2. (String Manipulation) is super friendly for anyone wanting to manage the reading / writing to and from files.

Thoughts? on doing just one, or both?

**Comment by addyosmani** [comment]
Thanks for thinking through a few usage scenarios. 

I could imagine someone working in Webpack wanting to consume swString and manipulate it before writing out to disk, but to be honest, given that this is a manifest being used specifically for our library I'm in favor of opting for option 1 for now and supporting option 2 if the need arises. Does that sound reasonable?
