### ISSUE TITLE
broadcast-cache-changes

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#43]
(I'm moving this here from https://github.com/GoogleChrome/sw-precache/issues/173)

**Library Affected**:
`broadcast-cache-changes`

The [Broadcast Channel API](https://developers.google.com/web/updates/2016/09/broadcastchannel?hl=en) ships in Chrome 54, and has already shipped in Firefox. It would be a good mechanism for allowing our service worker libraries to communicate with all of their client pages, without having to loop through them and use `postMessage()` to each one.

I'd like to see this used for cache updates notifications in `sw-precache` (see https://github.com/GoogleChrome/sw-precache/issues/47) and potentially other types of events in the future.

It's a good idea to standardize on the message format, and then to use a similar standardized format across our libraries. `sw-toolbox` recently implemented some one-to-one messaging (not using the Broadcast Channel API) that used messages like:

``` js
{
  type: 'cache-updated',
  source: 'sw-toolbox',
  cacheName: <name of cache>,
  url: <url of the updated resource>
}
```

But now I'm thinking that might be a bit too free-form, and not map well to new types of messages. I'd like to standardize on an implementation that could be shared across libraries, and then migrate `sw-toolbox` to that.

The [FSA message format](https://github.com/acdlite/flux-standard-action) has its roots in Flux, but at the same time, it's fl**e**xible enough just to be used as an all-purpose format, and since it appears to have some traction in the developer community, it might be a good choice.

I'm envisioning broadcasting messages like

``` js
{
  type: 'CACHE_UPDATED',
  meta: 'sw-precache', // or 'sw-toolbox', etc.
  payload: {
    cacheName: 'my-cache-name',
    updatedItems: [absoluteUrl1, absoluteUrl2, ...]
  }
}
```

My thinking is that the library should initially focus on just broadcasting `CACHE_UPDATED` for modifications made to previously cached entries, but perhaps down the line, it can be extended to broadcasting `CACHE_ADDED` and `CACHE_DELETED` messages as well.

As for the actual implementation of the code that would generate these messages, I'm going to prototype some approaches and see how they work out, and will share the results in this issue. My current thinking is that ES2015's [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) might lead to a clean implementation, but failing that, maybe just wrapping the Cache Storage API operations and exposing the wrapped methods via the new library.

CC: @addyosmani @gauntface @wibblymat @ebidel @NekR (in case this is something that he'd be interested in for https://github.com/NekR/offline-plugin)

**Comment by ebidel** [comment]
What's the idea with using a Proxy? Would you mind elaborating on that or sketching out a code example?

**Comment by deanhume** [comment]
+1 for the cache updates notifications in sw-precache!

**Comment by jeffposnick** [comment]
I've never written any code that uses `Proxy`, so this might be naive and I'd need to research the syntax. But my thinking is along the lines of:

```js
/* Inside broadcast-cache-changes.js */
function initialize(options) {
  // Set up a Proxy for Cache.add, Cache.addAll, and Cache.put
  // to intercept those calls. The code would make the cache modifications
  // and then use the Broadcast Channel API to announce what actually changed.
  // If the Broadcast Channel API is not available, this would be a no-op.
}

function destroy() {
  // Remove the Proxy?
}


/* Inside sw.js */
// Add goog.broadcastCacheChanges to our global scope.
importScripts('broadcast-cache-changes.js');

// Explicitly initialize the proxy behavior.
goog.broadcastCacheChanges.initialize({});

// cache.addAll will end up invoking our Proxy.
caches.open('my-cache').then(cache => cache.addAll(['index.html', 'app.js']));
```

An alternative would be to expose something like `broadcastCacheAdd()`, `broadcastCacheAddAll()`, `broadcastCachePut()` methods that developers could explicitly use, and would wrap the underlying Cache Storage API methods.

I'm open to other ideas, too!

**Comment by ebidel** [comment]
Proxies are copies of the original objects and changes need to be made to the proxied object rather than the original one. For example. https://gist.github.com/ebidel/1b553d571f924da2da06#file-object-observe-proxy-polyfill-js-L89-L97. It might be just as easy to override the original API call and wrap it.

**Comment by NekR** [comment]
BroadcastChannel API is great and update notifications is also a good idea, but what is the point of universal/standard messages for that? It makes sense for `sw-toolbox` and `sw-precache`, of course, because people are using them together, but I'm not sure about other libraries.

**Comment by jeffposnick** [comment]
Okay, thanks for the Proxy knowledge. Wrapping the Cache Storage API calls is probably the way to go, in that case.

I thought that some folks use `offline-plugin` + `sw-toolbox` together, @NekR, so I thought it might be nice if `offline-plugin` reported updates to cached files in a similar manner to whatever `sw-toolbox` ends up doing. This may not end up being a *de facto* standard or anything like that, but I wanted to give you a heads-up in case you were thinking of implementing something similar.

**Comment by NekR** [comment]
@jeffposnick Yeah, I suppose some people are using it together. I at least i suggested several times to do so if they want dynamic caching. I think, if you are going to adopt some common format for `sw-*` tools, then I'll be able to add support for that too, once I start handling such cases in `offline-plugin`.

**Comment by gauntface** [comment]
Presumably we'd use client.postMessage where broadcast channel isn't supported?

I'm +1 for type and payload but the `meta` parameter just doesn't make sense to me.

If I asked a new developer what they expect the contents of a value called `meta` to be, I don't think the answer would related to what it actually is. Either source, or simply 'name' would make more sense.

**Comment by jeffposnick** [comment]
`meta` is a concept from Flux Standard Actions: https://github.com/acdlite/flux-standard-action#meta

It's a question of whether we think there would be any benefit of adopting a "standard" format like FSA, in which case, `meta` would be the way to go for this sort of info. If we didn't care about adhering to FSA, then yeah, there are better naming choices. I'll take your comment as a vote in favor of not adhering to FSA.

Given that Firefox and Chrome (in Beta) both have implemented the Broadcast Channel API at this point, I'd rather point folks to a [Broadcast Channel API polyfill](https://gist.github.com/inexorabletash/52f437d1451d12145264) for folks who are concerned about older browsers than explicitly add in an alternative implementation.

**Comment by gauntface** [comment]
Got you. Does this mean we'll work better with react if we follow this standard? Are there any negatives beyond naming if we follow this? 

I'm not against a standard but I'm hesitant to say a framework standard is something we enforce given that if it changes to better fit changes to flux, will have to follow it? If no, then why take a poor naming convention?

**Comment by jeffposnick** [comment]
Yeah, there would be some Flux-synergies if we went with FSA. Though it's more of a case of avoiding creating something from scratch if there's a way of reusing a quasi-"standard".

If our `sw-helpers` libraries were the only ones who ever produce these types of messages, I wouldn't care too much, but I'd ideally like this to be something that catches on and other service worker libraries think about supporting as well. Being able to point to a specific message format could help ensure compatibility.

**Comment by jeffposnick** [comment]
See https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-broadcast-cache-update
