### ISSUE TITLE
Debug-level logging for when BroadcastCacheUpdate can't determine freshness

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/sw-helpers#441]
**Library Affected**:
sw-broadcast-cache-update

**Feature Request Description**:
Currently [sw-helpers/responses-are-same.js](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-broadcast-cache-update/src/lib/responses-are-same.js) differentiates two responses by looking at the etag, response-length, and last-modified headers.

Another approach would be to look at the response bodies. @samccone proposed using [SubtleCrypto.digest()](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) on the two response bodies. It takes an `arrayBuffer` and we have those handy in `response.body.arrayBuffer().then(ab => ...`

This could be an alternative or done in addition to the headers check.
This approach would make sense if the server doesn't issue last-modified or etag headers, and the change resulted in the same response-length.

**Comment by jeffposnick** [comment]
My thinking was that keeping things lightweight by not requiring Response body cloning, and not requiring the entirety of a (potentially large) body to be read into memory, would be the preferable default behavior. 

I could see adding in support for comparing full response bodies for folks who really need to do so, perhaps as a separate plugin subclass.

**Comment by paulirish** [comment]
Yah fair. Even python simplehttpserver includes last-modified headers, so perhaps just looking at headers is reliable enough.

**Comment by paulirish** [comment]
though perhaps a console.error should be issued if last-modified header is missing and the responses are determined to be the same.

**Comment by jeffposnick** [comment]
That's a perfect candidate for debug logs, sure. I'll repurpose this bug to track that?

**Comment by paulirish** [comment]
Sgtm.
