### ISSUE TITLE
Treat glob pattern with no file matches as a fatal error?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#449]
**Library Affected**:
*sw-build*

When using `sw-build` and passing in a glob pattern (either via `staticFileGlobs` or for a URL in `templatedUrls`), if that pattern doesn't match any files, then I *think* we should treat that as a fatal error that stops the build. It likely indicates that there's a developer error, perhaps because they don't realize how the `rootDirectory` comes into play, or because they don't know the glob pattern syntax.

I was thinking of something along the lines of adding this to https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/utils/get-file-details.js#L18:

```
if (globbedFiles.length === 0) {
  throw new Error(errors['useless-glob-pattern'] +
    JSON.stringify({rootDirectory, globPattern, globIgnores}));
}
```

How's that sound, @gauntface?

**Comment by jeffposnick** [comment]
And for some more context on why we might want a different behavior than `sw-precache`, which doesn't treat this as fatal: `sw-precache` logs info about the precache payload by default, and red flags like nothing matching a glob pattern could theoretically be inferred by reading the logged output. (`sw-precache` assuming that an inexperienced developer could properly infer which patterns needed to be fixed based on these log messages isn't very friendly.) 

We don't log that same sort of info in all of the various ways a developer might use `sw-build`.

**Comment by gauntface** [comment]
Totally agree to this proposal for sw-build.
