### ISSUE TITLE
sw-build always copy sw-lib in root-directory, does not consider dest key

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/sw-helpers#451]
**Library Affected**:
*sw-build*

**Browser & Platform**:
All

Currently if the I do sw-build something like:

```js
 swBuild.generateSW({
   rootDirectory: '/folderA',
   dest: '/myserviceworker.js'
 });
```

This ends up copying `sw-lib-0.18.0.min.js` into "/folderA" and "myserviceworker" at the right place.
But the "myserviceworker.js" still has code

```js
  importScripts('sw-lib.v0.0.18.min.js');
```

which should have been 

```js
  importScripts('/folderA/sw-lib.v0.0.18.min.js');
```

**Comment by prateekbh** [comment]
having different rootDirectory and desired location of `sw.js` will be a very common use case for `webpack` repos atleast.

**Comment by gauntface** [comment]
Totally agree - this is a bug, will fix asap.

**Comment by jeffposnick** [comment]
FWIW, I ran into (possibly related) path pain points while trying to use `injectManifest()` in a project earlier today. I'm going to file a issue when I get some time later tonight with full details including what my directory structure looked like, so if you're planning on changes, you might want to hold off until that.

**Comment by jeffposnick** [comment]
See #453 for an account of a different problem, albeit one also related to paths and `sw-build`.

**Comment by gauntface** [comment]
I'm going to kill two birds with one stone. The solution in #453 makes it clear in the code where this problem has come from. Should be fixed soon.
