### ISSUE TITLE
Unable to use injectManifest() for a given build setup

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#453]
CC: @gauntface 

**Library Affected**:
*sw-build*

Apologies as we may have touched on some of these options in code reviews, but it's hard to realize the pain points until you try something out in a real project.

I've got the following rough configuration:

```sh
src/
  sw.js
  sw.prod.js
  index.html
  static/
    js/
    css/
build/
  index.html
  static/
    js/
    css/
```

The development web server uses `src/` as root, and the production web server uses `build/` as root. `src/sw.js` is an empty, no-op service worker, and `src/sw.prod.js` uses the `swlib.precache([])` placeholder, along with some runtime caching rules.

I'm trying to come up with a configuration for `swBuild.injectManifest()` that will allow me to add the precaching info into `src/sw.prod.js`, with the result copied over to `build/sw.js`. The manifest generation takes place after the static files from `src/` have been versioned and copied over to `build/`.

Here's something that I've tried which doesn't work:

```js
swBuild.injectManifest({
  rootDirectory: 'build/',
  swFile: '../src/sw.prod.js',
  dest: '.',
  staticFileGlobs: [
    'index.html',
    'static/{js,css}/**/!(*map*)'
  ]
})
```

Setting `rootDirectory: 'build/'` seems like the right option, since that's the web root, and since the glob patterns that I've passed in assume that as the root directory. (Maybe I could set a different `rootDirectory` and then use `modifyUrlPrefix` to correct the manifest URLs, but `modifyUrlPrefix` isn't documented as being supported for the `injectManifest()` method.)

Setting `swFile: '../src/sw.prod.js'` is necessary because the `swFile` path is joined with `rootDirectory` in order to find the source service worker file.

I've tried setting `dest: '.'` or `dest: 'ignored'` and neither give me the output path that I want. `dest` is joined with `swFile` to compute the destination for the service worker file, and `swFile` includes `src/` as part of it's path (which I don't want as part of the output path), and it also has a filename of `sw.prod.js`, while I'd like the name to be `sw.js`.

I *think* the approach that would help is if the `swFile` and `dest` was considered as being relative to the current directory that the build script is running from, **not** relative to `rootDirectory`. It would also help if `dest` was required to be a path + filename, since otherwise you wouldn't be able to rename the output file.

**Comment by prateekbh** [comment]
I am running into the exact same issue with sw-build-webpack plugin

I have a structure like
```
lib/
    webpack.config.js
src/
    index.html
    sw.js
public/
    bundle.js
    sw-lin-0.18.0.min.js
```

1. Everything that webpack build, goes into public. 
2. In order to point to source Sw i user something like this

```js
new SwBuildWebpackPlugin({
	staticFileGlobs: ['*.{html,js,css}'],
	dest: '../public',
	clientsClaim: true,
	swFile: '../src/sw.js'
})
```

now this [line](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/inject-manifest.js#L88) tries to create `../public` which is fine and ends up creating 
`../public/../src/sw.js` and overrides my source `sw.js`

I guess at [line](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-build/src/lib/inject-manifest.js#L88) we should join a key named `swFileName || 'sw.js'` instead.

**Comment by gauntface** [comment]
Thanks for raising this. rootDirectory has always been a pain point from users.

Would it be worth dropping it completing and expecting developers to add it where appropriate as part of the glob patterns? The dest, could also be altered to be the service worker file path and just not join with swFile (i.e. swFile just becomes the input file, dest becomes the output file).

@jeffposnick @prateekbh to sum up:
- Remove rootDirectory and expect developer to add full path to globs
- Make swFile just the input
- Make dest the full output path

**Comment by jeffposnick** [comment]
Removing `rootDirectory` would make things less magic.

The concern that I have with removing it is that I'd expect that most developers will end up needing to use `modifyUrlPrefix`, since all of the globbed files would need the `public/` or `build/` or whatever prefix removed from their path to create a proper, production-ready URL.

I guess I come down in favor of removing `rootDirectory` and then augmenting the `modifyUrlPrefix` documentation in the process. As mentioned, `injectManifest()` doesn't currently list it in the JSDocs as being supported.

**Comment by prateekbh** [comment]
Removing `rootDirectory` would definitely make it more friendlier for build systems to append `globPatterns` accordingly.
and yes, `dest` should be a full output path as its pretty intuitive that ways

**Comment by gauntface** [comment]
Actually if I broke apart swFile and dest from rootDirectory, would that make everything a bit easier to reason with?

Then we could rename rootDirectory to something like globDirectory or something along those lines to it's clear rootDirectory is ONLY for globbing. Would that work?

**Comment by jeffposnick** [comment]
I'm on board with https://github.com/GoogleChrome/sw-helpers/issues/453#issuecomment-296770897
