### ISSUE TITLE
Deprecate sw-cacheable-response-behavior on npm

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#455]
**Library Affected**:
*sw-cacheable-response-behavior*

https://www.npmjs.com/package/sw-cacheable-response-behavior has been renamed to https://www.npmjs.com/package/sw-cacheable-response and the `0.0.8` release on `npm` should be deprecated (or unpublished, if that's still a thing).

I'd do it, but I don't have access to the `npm` entry.

**Comment by addyosmani** [comment]
👍

**Comment by gauntface** [comment]
Added you both to npm registry.

**Comment by jeffposnick** [comment]
Done.

```sh
[~]$ npm show sw-cacheable-response-behavior | grep deprecated
  deprecated: 'Moved to https://www.npmjs.com/package/sw-cacheable-response' }
```
