### ISSUE TITLE
Cannot find module './lib/constants'

### ISSUE THREAD

**Issue by oppianmatt** [GoogleChrome/sw-helpers#47]
**Library Affected**:

sw-offline-google-analytics,

**Browser & Platform**:

Chome 54.0.2840.59 m (64-bit) Windows 10

**Issue or Feature Request Description**:

Following the instructions, installed from npm and then added to service worker but getting the above error.

![image](https://cloud.githubusercontent.com/assets/48596/19446070/09aeed80-948f-11e6-9c09-f076d7970bfb.png)

Installed from npm using jspm, resulting directory structure is: 
![image](https://cloud.githubusercontent.com/assets/48596/19446143/51a3836c-948f-11e6-8dbb-f5a7094d0e6b.png)

```
importScripts('/static/jspm_packages/npm/sw-offline-google-analytics@1.1.1/offline-google-analytics-import.js');

// Then, call goog.offlineGoogleAnalytics.initialize():
// See https://github.com/GoogleChrome/sw-helpers/tree/master/projects/sw-offline-google-analytics#googofflinegoogleanalyticsinitialize
goog.offlineGoogleAnalytics.initialize();
```

**Comment by addyosmani** [comment]
Thanks for the bug report. I just tried using the npm module directly and everything appears to be working as expected (when importing from node_modules):

![](https://i.imgur.com/9LfdjR1.jpg)

Do you have a reduced test case using JSPM that you can share? It looks like there may be something tripping up the browserified builds we expose in your particular setup.

**Comment by oppianmatt** [comment]
Thanks for responding. Seems to be something to do with jspm and it's packaging. I tried the npm one directly and it works fine.

This is the gist of the offline-google-analytics-import.js script that comes from using jspm https://gist.github.com/oppianmatt/881f108be83cdde9e2e86e3b15665655

Service worker is just run like so in a script tag near the end of `body`:

```
    <script>
      if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('/service-worker.js');
      }
    </script>
```
In the service-worker.js itself, it's basically the https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/custom-offline-page/service-worker.js with offline analytics added in https://developers.google.com/web/updates/2016/07/offline-google-analytics

Tried:

- using importScripts to load the file from jspm_packages directory
- using importScripts to load system.js/config.js and then tried both using systemjs to import or importScripts

So tried these:

```
// load systemjs and config, this is ok, no errors
importScripts('{% static "jspm_packages/system.js" %}', '{% static "config.js" %}');

...

// try loading using module name (404)
importScripts('sw-offline-google-analytics');

// try loading directly from the jspm_packages dir (this the npm analogy)
importScripts('{% static "jspm_packages/npm/sw-offline-google-analytics@1.1.1/offline-google-analytics-import.js" %}');

// try loading module name + js file
importScripts('sw-offline-google-analytics/offline-google-analytics-import.js');

// try using systemjs loader
System.import('sw-offline-google-analytics').then(function(){
    goog.offlineGoogleAnalytics.initialize();
    console.log('offlineGoogleAnalytics init');
});
```

for completeness here is the service-worker.js as is (using the npm file) https://gist.github.com/oppianmatt/606eb39c3466e83f089f88784bc8da71

Although this feels like if it works in npm and not in jspm, then it must be jspm's issue and not yours. So might raise/point the jspm people to this issue

**Comment by oppianmatt** [comment]
@addyosmani I opened up a report on jspm here https://github.com/jspm/jspm-cli/issues/213

And the recommendation was to add an entry point to package.json

would that be possible?

**Comment by aluanhaddad** [comment]
If it is meant to be _imported_, IE required in a commonjs environment it really should have a main field. JSPM is not the only tool depending on this. TypeScript comes to mind, but there are probably countless other tools that also depend on this metadata and will be tripped up by this behavior as well. JSPM can read then `browser` property as well as several others, so it doesn't have to be main.

**Comment by aluanhaddad** [comment]
@oppianmatt Did you mean to link to jspm/jspm-cli/#2133, that is the issue you opened.

**Comment by oppianmatt** [comment]
@aluanhaddad oops, cut and paste fail. Fixed now, thanks for telling me

**Comment by gauntface** [comment]
This is going to be a *very* stupid question but what is the expectation of JSPM + one of the modules in this mono repo?

Does JSPM need a node style module.exports = moduleInstance, a ES6 export (export default moduleInstance)?

Finally would JSPM expect the raw source (i.e. allowing the developer manage their own bundling / minification / transpilation) or would it expect the bundling etc to be done?

I ask as I've been working on the bundling for some of the modules and want to make sure we are covering all bases.

**Comment by gauntface** [comment]
I'm going to close this for now. We've changed the structure of modules to include both minified and unminified versions of each sub-project, releasing a version for under `main` as well as `jsnext:main`. If there is anything actionable we can do to support your use case or a minimal repro so that we can investigate further please reopen :)
