### ISSUE TITLE
Silently failing sw-background-sync-queue tests

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#484]
**Library Affected**:
*sw-background-sync-queue*

While rewriting the build process, I was examining the tests for `sw-background-sync-queue` to make sure they continued to pass. I noticed that in the current `master` branch there are a number of failures that are logged to the JS console during test execution; they appear to the "silent" in that they don't cause any of the tests to fail. It's hard to copy the JS console text, but here's a screenshot from the current Chrome stable:

<img width="1364" alt="screen shot 2017-05-01 at 10 26 20 pm" src="https://cloud.githubusercontent.com/assets/1749548/25601910/8969cd24-2ebd-11e7-90ba-0ed5f3e582dd.png">

**Comment by prateekbh** [comment]
@jeffposnick raised a PR for this
