### ISSUE TITLE
Make the failing tests pass

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#50]
It's harder to understand the impact of new changes (and existing issues) with sub-projects when the tests have been failing for a while. Let's see if we can get them passing again before adding in new work. Right now it's hard to understand when the tests last actually went green (maybe 3 months ago? :))

Matt was up for trying to get the tests passing. Locally we're all green now on the appcache behavior. Just need to go green on offline analytics before that work lands.

**Comment by gauntface** [comment]
All tests are fixed now.
