### ISSUE TITLE
Different destination key

### ISSUE THREAD

**Issue by prateekbh** [GoogleChrome/sw-helpers#513]
**Library Affected**:
*sw-build*

**Browser & Platform**:
*All*

**Issue Description**:
why the destination key in injectManifest and generateSw different?

https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.20/module-sw-build.html

This will lead to confusion while using this API. a simple key name mismatch for the same functionality would want devs to remember which to use when. Or to keep visiting our documentation in order to check this.

**Comment by jeffposnick** [comment]
I think it should be `swDest` in both places.

@gauntface made the change in https://github.com/GoogleChrome/sw-helpers/pull/468 for `injectManifest()`; is there a reason why we wouldn't want the same change in `generateSw()`?

**Comment by gauntface** [comment]
Let's looks at some examples:

**Create Manifest**: Uses dest - /build/manifest.js
**Create Service Worker (+sw-lib)**: Uses dest - /build/sw.js
**InjectManifest**: Uses dest - /build/sw.js

I'm fine changes this to swDest for generateSW and inject manifest. I think I should also change the manifest to manifestDest - agreed?

**Comment by jeffposnick** [comment]
+1 for `swDest` throughout, and for using `manifestDest` for consistency.
