### ISSUE TITLE
Flakey "Generate SW End-to-End Tests"

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#516]
**Library Affected**:
*sw-appcache-behavior, sw-offline-google-analytics, etc.*

**Browser & Platform**:
*E.g. Google Chrome v51.0.1 for Android, or "all browsers".*

**Issue or Feature Request Description**:
*Your request here.*

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Comment by gauntface** [comment]
Could you share error messages when you spot this - that way we can see if there is a common issue to explore.

**Comment by jeffposnick** [comment]
Sorry, this was an incomplete dupe of https://github.com/GoogleChrome/sw-helpers/issues/517.

https://github.com/GoogleChrome/sw-helpers/issues/517 has a link to the AppVeyor build with the underlying error.
