### ISSUE TITLE
Decide on build artifacts per npm package

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#52]
**Library Affected**:
All

**Browser & Platform**:
All

Users have asked for us to consider including minified builds in our npm packages (#31). It might be nice to make a call on this so we can consistently apply it across the subprojects.

Fwiw, popular libraries like Lodash include both unminified and minified versions in their npm package.

![](https://i.imgur.com/owIsH3c.jpg)

**Comment by gauntface** [comment]
+1 .js and .min.js

Would also be something the CDN sites could reference.

**Comment by gauntface** [comment]
The built bundles are now minified.

One thing I need to ensure is that we work via:

- [ ] importScripts() or <script src="">
- [ ] import Router from "./build/router.js"
- [ ] require('./build/router.js')

**Comment by gauntface** [comment]
With Jeff's build work I think we can close this now.
