### ISSUE TITLE
Assertions + Errors

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#79]
@jeffposnick What would you think of adding the ability to pass in a custom error into the Assertions, this allows errors to customised to the use case and can follow a error.name and error.message pattern from the ErrorFactory.

**Comment by jeffposnick** [comment]
That sounds fine to me. I'm cognizant of your feedback about the assertion interface being heavyweight, though, so if there are opportunities to infer more information without it having to be explicitly provided, that would be a win. What would the modified interface look like?

**Comment by gauntface** [comment]
It's not so much that its heavyweight, just the wrapping that concerns me.

The sanest API would be to add a options argument to each method and use that to retrieve an option error, otherwise fallback to a default error.

```
function atLeastOne(object) {
  const parameters = Object.keys(object);
  if (!parameters.some((parameter) => object[parameter] !== undefined)) {
    throw Error('Please set at least one of the following parameters: ' +
      parameters.map((p) => `'${p}'`).join(', '));
  }
}
```

to

```
function atLeastOne(object, options = {}) {
  const parameters = Object.keys(object);
  if (!parameters.some((parameter) => object[parameter] !== undefined)) {
    throw options.error ? options.error :  Error('Please set at least one of the following parameters: ' +
      parameters.map((p) => `'${p}'`).join(', '));
  }
}
```

**Comment by jeffposnick** [comment]
That interface looks fine to me.

**Comment by gauntface** [comment]
This is related to #98 (Closing in favor of that)
