### ISSUE TITLE
Toggle assertions/debug logging via environment setting

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#93]
We should come up with a standard toggle for enabling/disabling assertions and additional logging via a central framework-level environment value (`'production'` or `'development'`).

The default value for that value, when not explicitly set, could be `'development'` if we detect that we're being served from `localhost`, and `'production'` otherwise.

**Comment by gauntface** [comment]
You've touched on two things that should probably be solved in similar ways.

1.) Assertions and code behavior depending on environment.
2.) Logging depending on environment.

**Comment by addyosmani** [comment]
> We should come up with a standard toggle for enabling/disabling assertions and additional logging via a central framework-level environment value ('production' or 'development').

This reminds me of the approach Webpack takes to this problem and I'm in favor of us adding support for it the way you've described (default to `dev` as much as we can reliably detect it).

**Comment by gauntface** [comment]
Pulling this issue back from the dead.

Does it make sense to add an additional level of filtering? I.e. info, debug, warn, error so that modules can use these as they see fit and developers can filter based on this (i.e. log level of 'info' would be everything, 'debug' would be just logs relating to behaviour, warnings is where modules can highlight possible issues, errors can be just logging of error messages)?

**Comment by gauntface** [comment]
I'm thinking of adding the following API for libraries to use:

```javascript
logHelper.log(...args);
logHelper.debug(...args);
logHelper.warn(...args);
logHelper.error(...args);
```

By default on localhost we can set the log level to debug or warn, and for production I'd say either no logging or error only (I'm in favor of no logs personally).

```javascript
class LogHelper {
  constructor() {
    this.LOG_LEVEL = {
        none: -1,
        verbose: 0,
        debug: 1,
        warn: 2,
        error: 3
    };
    this._allowedLogLevel = location.hostname === 'localhost' ? LOG_LEVEL.debug : LOG_LEVEL.none;
  }

  _printMessage(logLevel, logMethod, logArguments) {
    if (this._allowedLogLevel === LOG_LEVEL.none || logLevel < this._allowedLogLevel) {
        return;
    }
    logMethod(logArguments);
  }
}
```

@jeffposnick @addyosmani general thoughts on this or is this enough for me to make a start?

**Comment by gauntface** [comment]
p.s. I just hit an issue where it's not obvious why regex isn't resulting in a cache hit and logging seems like the best thing (that or I hit a bug).

**Comment by jeffposnick** [comment]
That, along with a setter to change the log level, looks 👍

**Comment by gauntface** [comment]
Awesome - I'll have a crack at this first thing next week I reckon.
