### ISSUE TITLE
Normalize ErrorFactory and assertion libraries

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#98]
Placeholder bug to remind myself that there's work to be done to normalize how we're using `Error` objects in the `assert` library and the `ErrorFactory` stuff.

More details to come.

**Comment by gauntface** [comment]
Minor thing to add on to this.

Was just moving the demos over and after fixing a few references, one issue I hit was this:

![](http://i.imgur.com/TQF5Fuk.png)

Generally these errors aren't too helpful. It doesn't explain where the cacheName is missing.
